# Wikiextractor

### Method 1

In [ ]:
!git clone https://github.com/attardi/wikiextractor.git

fatal: destination path 'wikiextractor' already exists and is not an empty directory.

In [ ]:
!wget https://dumps.wikimedia.org/simplewiki/latest/simplewiki-latest-pages-articles.xml.bz2

--2025-04-24 10:10:16--  https://dumps.wikimedia.org/simplewiki/latest/simplewiki-latest-pages-articles.xml.bz2
Resolving dumps.wikimedia.org (dumps.wikimedia.org)... 208.80.154.71, 2620:0:861:3:208:80:154:71
Connecting to dumps.wikimedia.org (dumps.wikimedia.org)|208.80.154.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 319539636 (305M) [application/octet-stream]
Saving to: ‘simplewiki-latest-pages-articles.xml.bz2.1’

simplewiki-latest-p 100%[===================>] 304.74M  4.50MB/s    in 68s

2025-04-24 10:11:24 (4.51 MB/s) - ‘simplewiki-latest-pages-articles.xml.bz2.1’ saved [319539636/319539636]

In [ ]:
!ls wikiextractor/wikiextractor

cirrus-extract.py  extractPage.py  __init__.py
clean.py	   extract.py	   WikiExtractor.py

In [ ]:
%cd /content/wikiextractor

/content/wikiextractor

In [ ]:
!python3 -m wikiextractor.WikiExtractor ../simplewiki-latest-pages-articles.xml.bz2 --json --output ../extracted

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/wikiextractor/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "/content/wikiextractor/wikiextractor/extract.py", line 382, in <module>
    ExtLinkBracketedRegex = re.compile(
                            ^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 4

In [ ]:
!sed -i '382,384c\\ExtLinkBracketedRegex = re.compile(r"(?i:\\[[^\\]]+\\])")\\' wikiextractor/extract.py

In [ ]:
%cd /content/wikiextractor

/content/wikiextractor

In [ ]:
!python3 -m wikiextractor.WikiExtractor ../simplewiki-latest-pages-articles.xml.bz2 --json --output ../extracted

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/wikiextractor/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "/content/wikiextractor/wikiextractor/extract.py", line 382
    ExtLinkBracketedRegex = re.compile(r"(?i:\[[^\]]+\])")
IndentationError: unexpected indent

In [ ]:
!sed -i '382c\ExtLinkBracketedRegex = re.compile(r"(?i:\\[[^\\]]+\\])")' wikiextractor/extract.py

In [ ]:
!python3 -m wikiextractor.WikiExtractor ../simplewiki-latest-pages-articles.xml.bz2 --json --output ../extracted

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/wikiextractor/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "/content/wikiextractor/wikiextractor/extract.py", line 382
    ExtLinkBracketedRegex = re.compile(r"(?i:\[[^\]]+\])")
IndentationError: unexpected indent

In [ ]:
!sed -i '382,384c\ExtLinkBracketedRegex = re.compile(r"(?i:\\[[^\\]]+\\])")' wikiextractor/extract.py

In [ ]:
!python3 -m wikiextractor.WikiExtractor ../simplewiki-latest-pages-articles.xml.bz2 --json --output ../extracted

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/wikiextractor/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "/content/wikiextractor/wikiextractor/extract.py", line 383, in <module>
    EXT_IMAGE_REGEX = re.compile(
                      ^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 95 (line 2, column 50)

### Method 2

In [ ]:
!pip install wikiextractor

Requirement already satisfied: wikiextractor in /usr/local/lib/python3.11/dist-packages (3.0.6)

Two versions of English Wikipedia Dump:  
https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2  
https://dumps.wikimedia.org/simplewiki/latest/simplewiki-latest-pages-articles.xml.bz2

We use the simplewiki, which is a smaller dataset

In [ ]:
!wget https://dumps.wikimedia.org/simplewiki/latest/simplewiki-latest-pages-articles.xml.bz2

--2025-04-24 18:50:57--  https://dumps.wikimedia.org/simplewiki/latest/simplewiki-latest-pages-articles.xml.bz2
Resolving dumps.wikimedia.org (dumps.wikimedia.org)... 208.80.154.71, 2620:0:861:3:208:80:154:71
Connecting to dumps.wikimedia.org (dumps.wikimedia.org)|208.80.154.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 319539636 (305M) [application/octet-stream]
Saving to: ‘simplewiki-latest-pages-articles.xml.bz2’

simplewiki-latest-p 100%[===================>] 304.74M  4.07MB/s    in 78s

2025-04-24 18:52:15 (3.91 MB/s) - ‘simplewiki-latest-pages-articles.xml.bz2’ saved [319539636/319539636]

In [ ]:
!python -m wikiextractor.WikiExtractor enwiki-latest-pages-articles.xml.bz2 --output extracted

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/wikiextractor/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "/content/wikiextractor/wikiextractor/extract.py", line 382, in <module>
    ExtLinkBracketedRegex = re.compile(
                            ^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 4

This issue arises because, starting with Python 3.11, the re module enforces that inline flags like (?i) must appear at the very beginning of the regular expression. In WikiExtractor's version 3.0.6, some regular expressions violate this rule, leading to the error you're seeing.​

In [ ]:
!pip install --upgrade wikiextractor

Collecting wikiextractor
  Downloading wikiextractor-3.0.6-py3-none-any.whl.metadata (7.3 kB)
Downloading wikiextractor-3.0.6-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 2.3 MB/s eta 0:00:00
Installing collected packages: wikiextractor
Successfully installed wikiextractor-3.0.6

In [ ]:
!pip show wikiextractor

Name: wikiextractor
Version: 3.0.6
Summary: A tool for extracting plain text from Wikipedia dumps
Home-page: https://github.com/attardi/wikiextractor
Author: Giuseppe Attardi
Author-email: attardi@gmail.com
License: GNU Affero General Public License
Location: /usr/local/lib/python3.11/dist-packages
Requires:
Required-by:

In [ ]:
import re

path = '/usr/local/lib/python3.11/dist-packages/wikiextractor/extract.py'

# Read original content
with open(path, 'r') as file:
    content = file.read()

# Define regex pattern and replacement
pattern = r'(?i)([^ ]+)'               # problematic pattern
replacement = r'(?i:[^ ]+)'            # Python 3.11-compatible version

# Check using re.search
if re.search(pattern, content):
    print("Found regex pattern, replacing...")
    content = re.sub(pattern, replacement, content)

    # Write modified content back
    with open(path, 'w') as file:
        file.write(content)

    print("Replacement done.")
else:
    print("Pattern not found — no changes made.")

Found regex pattern, replacing...
Replacement done.

In [ ]:
# Confirm it's replaced
with open(path, 'r') as file:
    if replacement in file.read():
        print("Confirmed: content was replaced.")
    else:
        print("Warning: replacement not found.")

Confirmed: content was replaced.

In [ ]:
!python -m wikiextractor.WikiExtractor enwiki-latest-pages-articles.xml.bz2 --output extracted

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "/usr/local/lib/python3.11/dist-packages/wikiextractor/extract.py", line 1
    ]+)    (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)    (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)    (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)        (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)    (?i:[^ ]+) (?i:[^ ]+)        (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)    (?i:[^ ]+)        (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)    (?i:[^ ]+) (?i:[^ ]+)        (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)            (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)        (?i:[^ ]+) (?i:[^ ]+) (?i:[^ ]+)
    ^
SyntaxError: invalid syntax

In [ ]:
!pip uninstall -y wikiextractor
!pip install wikiextractor

Found existing installation: wikiextractor 3.0.6
Uninstalling wikiextractor-3.0.6:
  Successfully uninstalled wikiextractor-3.0.6
Collecting wikiextractor
  Using cached wikiextractor-3.0.6-py3-none-any.whl.metadata (7.3 kB)
Using cached wikiextractor-3.0.6-py3-none-any.whl (46 kB)
Installing collected packages: wikiextractor
Successfully installed wikiextractor-3.0.6

In [ ]:
import re

path = '/usr/local/lib/python3.11/dist-packages/wikiextractor/extract.py'

# Read the original file
with open(path, 'r') as file:
    content = file.read()

# This matches lines where inline flags are used inside the pattern and moves them to the start
content_fixed = re.sub(
    r"re\.compile\(\s*r(['\"])\[(\?\w\))([^\]]+)\]\1",
    r"re.compile(r'\1(?i)\[\3\]')",
    content
)

# Only write back if a change was made
if content != content_fixed:
    with open(path, 'w') as file:
        file.write(content_fixed)
    print("✅ Regex compatibility fix applied.")
else:
    print("ℹ️ No changes made — patterns may already be fixed.")

ℹ️ No changes made — patterns may already be fixed.

In [ ]:
!python -m wikiextractor.WikiExtractor enwiki-latest-pages-articles.xml.bz2 --output extracted

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "/usr/local/lib/python3.11/dist-packages/wikiextractor/extract.py", line 378, in <module>
    ExtLinkBracketedRegex = re.compile(
                            ^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 4

### Method 3
Reference: https://github.com/attardi/wikiextractor/issues/336

In [ ]:
!pip uninstall wikiextractor
!pip install git+https://github.com/attardi/wikiextractor.git@ab8988ebfa9e4557411f3d4c0f4ccda139e18875

Found existing installation: wikiextractor 3.0.7
Uninstalling wikiextractor-3.0.7:
  Would remove:
    /usr/local/bin/extractPage
    /usr/local/bin/wikiextractor
    /usr/local/lib/python3.11/dist-packages/wikiextractor-3.0.7.dist-info/*
    /usr/local/lib/python3.11/dist-packages/wikiextractor/*
Proceed (Y/n)? y
  Successfully uninstalled wikiextractor-3.0.7
Collecting git+https://github.com/attardi/wikiextractor.git@ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Cloning https://github.com/attardi/wikiextractor.git (to revision ab8988ebfa9e4557411f3d4c0f4ccda139e18875) to /tmp/pip-req-build-issngxht
  Running command git clone --filter=blob:none --quiet https://github.com/attardi/wikiextractor.git /tmp/pip-req-build-issngxht
  Running command git rev-parse -q --verify 'sha^ab8988ebfa9e4557411f3d4c0f4ccda139e18875'
  Running command git fetch -q https://github.com/attardi/wikiextractor.git ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Running command git checkout -q ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Resolved https://github.com/attardi/wikiextractor.git to commit ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wikiextractor
  Building wheel for wikiextractor (setup.py) ... done
  Created wheel for wikiextractor: filename=wikiextractor-3.0.7-py3-none-any.whl size=47605 sha256=03afd319ce44e3ff52b843545a3a961746111b7cc6cc0f484d4a0a48e0eff416
  Stored in directory: /root/.cache/pip/wheels/aa/7c/fa/5d3adccb0fc93c22d5710082a349928c889caa4aaf8f1a3112
Successfully built wikiextractor
Installing collected packages: wikiextractor
Successfully installed wikiextractor-3.0.7

In [ ]:
!wget https://dumps.wikimedia.org/simplewiki/latest/simplewiki-latest-pages-articles.xml.bz2

--2025-04-25 10:11:52--  https://dumps.wikimedia.org/simplewiki/latest/simplewiki-latest-pages-articles.xml.bz2
Resolving dumps.wikimedia.org (dumps.wikimedia.org)... 208.80.154.71, 2620:0:861:3:208:80:154:71
Connecting to dumps.wikimedia.org (dumps.wikimedia.org)|208.80.154.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 319539636 (305M) [application/octet-stream]
Saving to: ‘simplewiki-latest-pages-articles.xml.bz2.1’

simplewiki-latest-p 100%[===================>] 304.74M  3.80MB/s    in 79s

2025-04-25 10:13:11 (3.84 MB/s) - ‘simplewiki-latest-pages-articles.xml.bz2.1’ saved [319539636/319539636]

It takes too much time to extract all the Simple English Wikipedia articles. 1 hour +
So decompress and grab just the start of the file by adding "head -n 500000"

In [ ]:
!bzcat simplewiki-latest-pages-articles.xml.bz2 | head -n 500000 > partial.xml

In [ ]:
!python -m wikiextractor.WikiExtractor partial.xml --output extracted_500000

INFO: Preprocessing 'partial.xml' to collect template definitions: this may take some time.
INFO: Loaded 87 templates in 0.3s
INFO: Starting page extraction from partial.xml.
INFO: Using 1 extract processes.
WARNING: Template errors in article 'Combinatorial game theory' (3692): title(1) recursion(0, 0, 0)
INFO: Finished 1-process extraction of 4237 articles in 12.5s (339.2 art/s)

In [ ]:
import os
print(os.getcwd())

/content

In [ ]:
!ls

extracted	  simplewiki-latest-pages-articles.xml.bz2
extracted_100000  simplewiki-latest-pages-articles.xml.bz2.1
extracted_500000  tawiki-latest-pages-articles.xml.bz2
partial.xml	  wikiextractor
sample_data

In [ ]:
with open('/content/partial.xml', 'r') as f:
    print(f.read(40000))  # Preview the first 40000 characters

<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.11/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.11/ http://www.mediawiki.org/xml/export-0.11.xsd" version="0.11" xml:lang="en">
  <siteinfo>
    <sitename>Wikipedia</sitename>
    <dbname>simplewiki</dbname>
    <base>https://simple.wikipedia.org/wiki/Main_Page</base>
    <generator>MediaWiki 1.44.0-wmf.25</generator>
    <case>first-letter</case>
    <namespaces>
      <namespace key="-2" case="first-letter">Media</namespace>
      <namespace key="-1" case="first-letter">Special</namespace>
      <namespace key="0" case="first-letter" />
      <namespace key="1" case="first-letter">Talk</namespace>
      <namespace key="2" case="first-letter">User</namespace>
      <namespace key="3" case="first-letter">User talk</namespace>
      <namespace key="4" case="first-letter">Wikipedia</namespace>
      <namespace key="5" case="first-letter">Wikipedia talk</namespace>
      <namespace key="6" case="first-letter">File</namespace>
      <namespace key="7" case="first-letter">File talk</namespace>
      <namespace key="8" case="first-letter">MediaWiki</namespace>
      <namespace key="9" case="first-letter">MediaWiki talk</namespace>
      <namespace key="10" case="first-letter">Template</namespace>
      <namespace key="11" case="first-letter">Template talk</namespace>
      <namespace key="12" case="first-letter">Help</namespace>
      <namespace key="13" case="first-letter">Help talk</namespace>
      <namespace key="14" case="first-letter">Category</namespace>
      <namespace key="15" case="first-letter">Category talk</namespace>
      <namespace key="126" case="first-letter">MOS</namespace>
      <namespace key="127" case="first-letter">MOS talk</namespace>
      <namespace key="710" case="first-letter">TimedText</namespace>
      <namespace key="711" case="first-letter">TimedText talk</namespace>
      <namespace key="828" case="first-letter">Module</namespace>
      <namespace key="829" case="first-letter">Module talk</namespace>
    </namespaces>
  </siteinfo>
  <page>
    <title>April</title>
    <ns>0</ns>
    <id>1</id>
    <revision>
      <id>9718138</id>
      <parentid>9588104</parentid>
      <timestamp>2024-08-22T02:32:44Z</timestamp>
      <contributor>
        <username>Auntof6</username>
        <id>22027</id>
      </contributor>
      <minor />
      <comment>Fixing links to disambiguation pages and/or general cleanup using [[Project:AWB|AWB]]</comment>
      <origin>9718138</origin>
      <model>wikitext</model>
      <format>text/x-wiki</format>
      <text bytes="22096" sha1="n8qtu37llvow70munkc97l1syqsj9dw" xml:space="preserve">{{monththisyear|4}}
'''April''' (Apr.) is the fourth [[month]] of the [[year]] in the [[Julian calendar|Julian]] and [[Gregorian calendar]]s, and comes between [[March]] and [[May]]. It is one of four months to have 30 [[day]]s.

April always begins on the same day of the week as [[July]], and additionally, [[January]] in leap years. April always ends on the same day of the week as [[December]].

== The Month ==
[[File:Colorful spring garden.jpg|thumb|180px|right|[[Spring (season)|Spring]] flowers in April in the [[Northern Hemisphere]].]]
April comes between [[March]] and [[May]], making it the fourth month of the year. It also comes first in the year out of the four months that have 30 days, as [[June]], [[September]] and [[November]] are later in the year.

April begins on the same day of the week as [[July]] every year and on the same day of the week as [[January]] in [[leap year]]s. April ends on the same day of the week as [[December]] every year, as each other's last days are exactly 35 weeks (245 days) apart.

In [[common year]]s, April starts on the same day of the week as [[October]] of the previous year, and in [[leap year]]s, [[May]] of the previous year. In common years, April finishes on the same day of the week as [[July]] of the previous year, and in leap years, [[February]] and [[October]] of the previous year. In common years immediately after other common years, April starts on the same day of the week as [[January]] of the previous year, and in leap years and years immediately after that, April finishes on the same day of the week as January of the previous year.

In years immediately before common years, April starts on the same day of the week as [[September]] and [[December]] of the following year, and in years immediately before leap years, [[June]] of the following year. In years immediately before common years, April finishes on the same day of the week as September of the following year, and in years immediately before leap years, [[March]] and June of the following year.

April is a [[Spring (season)|spring]] month in the [[Northern Hemisphere]] and an [[autumn|autumn/fall]] month in the [[Southern Hemisphere]]. In each [[hemisphere]], it is the [[season]]al equivalent of [[October]] in the other.

It is unclear as to where April got its name. A common theory is that it comes from the [[Latin]] word &quot;aperire&quot;, meaning &quot;to open&quot;, referring to [[flower]]s opening in [[Spring (season)|spring]]. Another theory is that the name could come from [[Aphrodite]], the Greek goddess of [[love]]. It was originally the second month in the old Roman [[Calendar]], before the start of the new year was put to [[January 1]].

Quite a few festivals are held in this month. In many [[Southeast Asia]]n cultures, new year is celebrated in this month (including [[Songkran]]). In Western [[Christianity]], [[Easter]] can be celebrated on a [[Sunday]] between [[March 22]] and [[April 25]]. In [[Eastern Orthodox Church|Orthodox]] Christianity, it can fall between [[April 4]] and [[May 8]]. At the end of the month, Central and Northern [[Europe]]an [[culture]]s celebrate [[Walpurgis Night]] on [[April 30]], marking the transition from [[winter]] into [[summer]].

== April in poetry ==
[[poetry|Poets]] use ''April'' to mean the end of winter. For example: ''April showers bring [[May]] flowers.''

== Events in April ==
=== Fixed Events ===
[[File:Aprilsnar 2001.png|thumb|200px|right|An [[April Fools' Day]] hoax for [[April 1]] in [[Copenhagen]].]]
[[File:Songkran in Wat Kungthapao 03.jpg|thumb|180px|right|[[Songkran]] celebration in [[Thailand]] around [[April 14]].]]
[[File:Earth flag PD.jpg|thumb|200px|right|Proposed [[flag]] for [[Earth Day]] on [[April 22]].]]
[[File:St George's Day 2010 - 14.jpg|thumb|200px|right|[[Saint George]]'s Day on [[April 23]] in [[London]]'s [[Trafalgar Square]].]]
[[File:Anzac1.JPG|thumb|180px|right|[[ANZAC Day]] commemoration in [[Australia]] on [[April 25]].]]
[[File:Koninginnedag2007.jpg|thumb|180px|right|Queen's Day, [[April 30]], celebration in the [[Netherlands]]. It changed to King's Day, [[April 27]], in [[2014]].]]
[[File:Valborgsbrasa-1.jpg|thumb|210px|right|[[Walpurgis Night]] bonfire on [[April 30]] in [[Sweden]].]]
* [[April 1]] - [[April Fools' Day]]
* [[April 1]] - Islamic Republic Day ([[Iran]])
* [[April 2]] - International Children's Book Day
* [[April 2]] - [[Thailand|Thai]] Heritage and [[wikt:conservation|Conservation]] Day
* [[April 2]] - World [[Autism]] Awareness Day
* [[April 2]] - Malvinas Day ([[Argentina]])
* [[April 4]] - Independence Day ([[Senegal]])
* [[April 4]] - International Day for Landmine Awareness and Assistance
* [[April 4]] - Peace Day ([[Angola]])
* [[April 5]] - End of [[Tax]] Year ([[United Kingdom]])
* [[April 6]] - Tartan Day ([[Canada]] and [[United States]])
* [[April 6]] - Chakri Day ([[Thailand]])
* [[April 7]] - Day of Maternity and Beauty ([[Armenia]])
* [[April 7]] - Genocide Memorial Day ([[Rwanda]])
* [[April 7]] - World [[Health]] Day
* [[April 7]] - Women's Day ([[Mozambique]])
* [[April 8]] - [[The Buddha|Buddha]]'s Birthday ([[Buddhism]])
* [[April 9]] - Martyrs' Day ([[Tunisia]])
* [[April 9]] - Day of National Unity ([[Georgia (country)|Georgia]])
* [[April 9]] - Day of the [[Finnish language]]
* [[April 12]] - [[Cosmonaut]]s' Day ([[Russia]]), marking the day of [[Yuri Gagarin]]'s space flight
* [[April 13]] - Songkan ([[Laos]]), local New Year celebration
* [[April 13]] - [[Cambodia]]n New Year
* [[April 13]] - [[Thomas Jefferson]]'s [[Birthday]] ([[United States]])
* [[April 14]] - [[Southeast Asia]]n [[New Year]] festivals, including [[Songkran]]
* [[April 14]] - [[Georgian language]] Day
* [[April 14]] - Youth Day ([[Angola]])
* [[April 14]] - Ambedkar Jayanti ([[India]])
* [[April 14]] - Pan-American Day
* [[April 15]] - [[Tax]] Day ([[United States]])
* [[April 15]] - [[Kim Il-Sung]]'s [[Birthday]] ([[North Korea]])
* [[April 15]] - [[Father Damien]] Day ([[Hawaii]])
* [[April 15]] - [[Jackie Robinson]] Day ([[Major League Baseball]])
* [[April 16]] - [[Birthday]] of Queen [[Margrethe II of Denmark]]
* [[April 16]] - Emancipation Day ([[Washington, DC]])
* [[April 16]] - World [[Voice]] Day
* [[April 16]] - [[Selena]] Day ([[Texas]])
* [[April 17]] - National Day of [[Syria]]
* [[April 17]] - Flag Day ([[American Samoa]])
* [[April 17]] - Women's Day ([[Gabon]])
* [[April 17]] - World [[Hemophilia]] Day
* [[April 18]] - Independence Day ([[Zimbabwe]])
* [[April 18]] - Invention Day ([[Japan]])
* [[April 18]] - International Day of [[Monument]]s and Sites
* [[April 19]] - [[Bicycle]] Day
* [[April 19]] - Dutch-American Friendship Day
* [[April 19]] - [[Birthday]] of King [[Mswati III]] of [[Swaziland]]
* [[April 19]] - Patriots' Day ([[Massachusetts]], [[Maine]], [[Wisconsin]])
* [[April 20]] - 4/20 in [[Cannabis]] [[Culture]]
* [[April 21]] - [[John Muir]] Day ([[California]])
* [[April 21]] - San Jacinto Day ([[Texas]])
* [[April 21]] - Kartini Day ([[Indonesia]])
* [[April 21]] - National [[Tree]] Planting Day ([[Kenya]])
* [[April 21]] - First Day of [[Ridran]] ([[Baha'i]] faith)
* [[April 21]] - Grounation Day ([[Rastafari movement]])
* [[April 22]] - [[Earth Day]]
* [[April 22]] - Discovery Day ([[Brazil]])
* [[April 23]] - [[Saint George]]'s Day, celebrating the patron saint of several countries, regions and cities (including [[England]] and [[Catalonia]])
* [[April 23]] - World [[Book]] Day
* [[April 23]] - National Sovereignty and [[Child]]ren's Day ([[Turkey]])
* [[April 24]] - Democracy Day ([[Nepal]])
* [[April 24]] - Genocide Day ([[Armenia]])
* [[April 24]] - [[Republic]] Day (the [[Gambia]])
* [[April 25]] - [[Australia]] and [[New Zealand]] celebrate [[ANZAC Day]]. [http://www.awm.gov.au/dawn/spirit/meaning.asp ANZAC] {{Webarchive|url=https://web.archive.org/web/20060615053606/http://www.awm.gov.au/dawn/spirit/meaning.asp |date=2006-06-15 }} means Australian and New Zealand Army Corps, and began in 1915.
* [[April 25]] - World [[DNA]] Day
* [[April 25]] - World [[Malaria]] Day
* [[April 25]] - Flag Day ([[Swaziland]], [[Faroe Islands]])
* [[April 25]] - Freedom Day ([[Portugal]])
* [[April 25]] - Liberation Day ([[Italy]])
* [[April 25]] - Army Day ([[North Korea]])
* [[April 26]] - Union Day ([[Tanzania]])
* [[April 26]] - Confederate Memorial Day ([[Texas]], [[Florida]])
* [[April 27]] - Independence Day ([[Sierra Leone]] and [[Togo]])
* [[April 27]] - Freedom Day ([[South Africa]])
* [[April 27]] - World [[Tapir]] Day
* [[April 27]] - King's Day ([[Netherlands]]) from [[2014]], birthday of [[Willem-Alexander of the Netherlands]]
* [[April 28]] - Workers Memorial Day
* [[April 28]] - National Day ([[Sardinia]])
* [[April 28]] - National Heroes Day ([[Barbados]])
* [[April 29]] - Showa Day ([[Japan]]), birthday of Emperor [[Hirohito]], who died in [[1989]]
* [[April 29]] - International [[Dance]] Day
* [[April 30]] - Former Queen's Day Holiday in the [[Netherlands]] (changed to King's Day, [[April 27]] in [[2014]]), was the birthday of former Queen [[Juliana of the Netherlands]]
* [[April 30]] - Flag Day in [[Sweden]] (birthday of King [[Carl XVI Gustaf of Sweden]])
* [[April 30]] - International [[Jazz]] Day
* [[April 30]] - [[Walpurgis Night]] (Central and Northern [[Europe]])

=== Moveable Events ===
[[File:Vajicka1.jpg|thumb|200px|right|Eggs celebrating [[Easter]], which often falls in April, but sometimes falls in [[March]].]]
[[File:Aprilregen - Lithografie.jpg|thumb|200px|right|Image traditionally showing it as [[rain]]ing in April in the [[Northern Hemisphere]].]]
* [[Easter]]-related events in Western [[Christianity]]:
** Palm Sunday (between [[March 15]] and [[April 18]])
** Maundy Thursday (between [[March 19]] and [[April 22]])
** Good Friday (between [[March 20]] and [[April 23]])
** [[Easter]] Sunday (between [[March 22]] and [[April 25]])
** Easter Monday (between [[March 23]] and [[April 26]])
* Eastern Orthodox Easter falls between [[April 4]] and [[May 8]].
* Ascension Day (Western Christianity), falls between [[April 30]] and [[June 3]].
* [[Judaism|Jewish]] [[Passover]] - falls in the same week as Western [[Christianity]]'s [[Holy Week]], which is the week leading up to [[Easter]].
* [[Mother's Day]] ([[UK]]) falls between [[March 1]] and [[April 4]].
* World [[Snooker]] Championship (late April, early [[May]])
* [[Horse racing]] - [[Grand National]] ([[UK]]), [[Kentucky Derby]] ([[United States]])
* Start of [[Daylight Saving Time]] - Clocks going forward one hour:
** Most of [[Mexico]]
** [[Morocco]] ([[Ramadan]] does not include Daylight Saving Time)
* End of [[Daylight Saving Time]] - Clocks going back one hour:
** Southeast [[Australia]], and [[New Zealand]]
** [[Chile]]
* [[Marathon]] Events in the following cities:
** [[Belgrade]], [[Serbia]]
** [[Boston, Massachusetts]], [[United States]]
** [[Brighton]], [[United Kingdom]]
** [[Enschede]], [[Netherlands]]
** [[London]], [[United Kingdom]] (held in [[October]] from [[2020]] to [[2022]] because of [[COVID-19]])
** [[Madrid]], [[Spain]]
** [[Paris]], [[France]]
** [[Rotterdam]], [[Netherlands]]
** [[Utrecht (city)|Utrecht]], [[Netherlands]]
** [[Zurich]], [[Switzerland]]

== Selection of Historical Events ==
[[File:Nunavut-Feierlichkeit (01-04-99).jpg|thumb|180px|right|[[Inauguration]] celebration for [[Nunavut]] on [[April 1]], [[1999]].]]
[[File:Moai Rano raraku.jpg|thumb|160px|right|A statue on [[Easter Island]] - Jacob Roggeveen became the first [[Europe]]an to land there on [[April 5]], [[1722]].]]
[[File:Titanic-New York Herald front page.jpeg|thumb|150px|right|[[Newspaper]] report on the sinking of the [[RMS Titanic]] on [[April 15]], [[1912]].]]
[[File:San Francisco Fire Sacramento Street 1906-04-18.jpg|thumb|180px|right|[[Fire]]s after the [[San Francisco]] [[earthquake]] on [[April 18]], [[1906]].]]
[[File:Anzac Beach 4th Bn landing 8am April 25 1915.jpg|thumb|180px|right|[[Australia]]n and [[New Zealand]] forces landing at Anzac Cove, [[April 25]], [[1915]].]]
[[File:HMS Bounty.jpg|thumb|200px|right|Painting showing the Mutiny on the Bounty on [[April 28]], [[1789]].]]
[[File:Juliana 1959.jpg|thumb|150px|right|Queen [[Juliana of the Netherlands]], who abdicated the throne on her 71st [[birthday]], [[April 30]], [[1980]].]]
* [[April 1]], [[1918]] - The [[Royal Air Force]] is founded.
* [[April 1]], [[1976]] - [[Apple Inc.]] is founded.
* [[April 1]], [[1979]] - The [[Islamic Republic of Iran]] is founded.
* [[April 1]], [[1999]] - The [[territory]] of [[Nunavut]] is created in Northern [[Canada]].
* [[April 1]], [[2001]] - The [[Netherlands]] introduces [[same-sex marriage]], as the first [[country]] to do so.
* [[April 2]], [[1519]] - [[Florida]] is sighted by a [[Europe]]an for the first time.
* [[April 2]], [[1930]] - [[Haile Selassie]] becomes [[Emperor of Ethiopia]].
* [[April 2]], [[1982]] - Start of the [[Falklands War]], as Argentine forces land on the [[Falkland Islands]].
* [[April 2]], [[2005]] - [[Pope John Paul II]] dies aged 84, after {{frac|26|1|2}} years as [[Pope]].
* [[April 3]], [[1973]] - The first-ever [[mobile phone]] call is placed by Martin Cooper in [[New York City]].
* [[April 4]], [[1721]] - [[Robert Walpole]] becomes the first [[Prime Minister]] of [[Great Britain]].
* [[April 4]], [[1841]] - [[William Henry Harrison]] dies. He was [[President of the United States]] for 31 days, the shortest-ever time in office for a US president.
* [[April 4]], [[1960]] - [[Senegal]] becomes independent.
* [[April 4]], [[1968]] - [[Assassination]] of [[Martin Luther King, Jr.]] in [[Memphis, Tennessee]].
* [[April 5]], [[1722]] - [[Jacob Roggeveen]] becomes the first [[Europe]]an to land on [[Easter Island]], landing there on [[Easter]] Sunday.
* [[April 6]], [[1320]] - [[Scotland]]'s independence is confirmed with the Declaration of [[Arbroath]].
* [[April 6]], [[1830]] - The [[Mormonism|Mormon]] Church is founded.
* [[April 6]], [[1909]] - [[Robert Peary]] claims to have been first at the [[North Pole]] on this date.
* [[April 7]], [[1994]] - The [[Rwandan Genocide]] begins.
* [[April 9]], [[1865]] - [[American Civil War]]: [[Confederate States of America|Confederate]] forces under [[Robert E. Lee]] surrender to Union forces.
* [[April 9]], [[1940]] - [[World War II]]: [[Denmark]] and [[Norway]] are invaded by [[Nazi]] [[Germany]].
* [[April 9]], [[1989]] - April 9 tragedy: In [[Tbilisi]], [[Georgia (country)|Georgia]], a peaceful demonstration for independence is broken up by the [[Soviet]] [[Army]], killing 20 people. The country gains independence on this date exactly two years later.
* [[April 10]], [[1815]] - Mount [[Tambora]] in [[Indonesia]] erupts in a huge eruption, affecting the world's climate for at least a year.
* [[April 10]], [[2010]] - A [[fixed-wing aircraft|plane]] crash near Smolensk, [[Russia]], kills several people who were important in [[Poland]], including [[President]] [[Lech Kaczynski]].
* [[April 11]], [[1814]] - [[Napoleon Bonaparte]] is [[exile]]d to the [[island]] of [[Elba]].
* [[April 11]], [[1954]] - Said to have been the most boring day of the [[20th century]].
* [[April 12]], [[1861]] - The [[American Civil War]] begins at [[Fort Sumter]], [[Charleston, South Carolina]].
* [[April 12]], [[1945]] - US President [[Franklin D. Roosevelt]] dies, and [[Harry S. Truman]] replaces him.
* [[April 12]], [[1961]] - [[Yuri Gagarin]] becomes the first [[human]] to fly into [[Outer space|space]].
* [[April 14]], [[1865]] - US President [[Abraham Lincoln]] is shot dead at Ford's Theatre by [[John Wilkes Booth]]. Lincoln dies the next day.
* [[April 14]], [[2010]] - [[Qinghai]] Province, [[China]], is hit by an [[earthquake]], killing tens of thousands of people.
* [[April 14]], [[2010]] - The eruption of [[Eyjafjallajokull]] in [[Iceland]] shuts down air traffic around [[Europe]] for a week, due to its ash cloud.
* [[April 15]], [[1912]] - The [[ship]] [[RMS Titanic]] sinks near [[Newfoundland]] after hitting an iceberg, resulting in the deaths of many of the people on board.
* [[April 16]], [[1943]] - [[Albert Hofmann]] discovers [[LSD]]'s effects.
* [[April 17]], [[1946]] - [[Syria]] gains full independence from [[France]].
* [[April 17]], [[1955]] - [[Albert Einstein]] dies.
* [[April 18]], [[1906]] - [[1906 San Francisco earthquake]]: [[San Francisco]], [[California]], is hit by a big [[earthquake]], resulting in [[fire]]s that destroy large parts of the city.
* [[April 18]], [[1980]] - [[Zimbabwe]] gains full independence.
* [[April 19]], [[1897]] - The first [[Boston Marathon]] is held.
* [[April 19]], [[1971]] - [[Sierra Leone]] becomes a [[republic]].
* [[April 19]], [[1993]] - The siege of the Branch Davidians at Waco, [[Texas]], ends in a fire that kills 82 people.
* [[April 19]], [[1995]] - [[Timothy McVeigh]] carries out the [[Oklahoma City bombing]], killing 169 people.
* [[April 19]], [[2005]] - Joseph Alois Ratzinger becomes [[Pope Benedict XVI]].
* [[April 20]], [[1889]] - [[Adolf Hitler]] is born.
* [[April 20]], [[1902]] - [[Marie Curie]] and [[Pierre Curie]] refine [[Radium]].

looks like the data is not cleaned yet, tried to clean the data by using the clean.py inside the Wikiextractor. Then realized it is not necessary. The data is already cleaned after extarcting.

#### print and verify
returncode=0 means success

In [ ]:
extracted_dir = 'extracted_500000'

# List all files and subdirectories in the directory
files_and_subdirs = os.listdir(extracted_dir)

print(files_and_subdirs)

['AA']

In [ ]:
extracted_dir = 'extracted_500000/AA'

# List all files and subdirectories in the directory
files_and_subdirs = os.listdir(extracted_dir)

print(files_and_subdirs)

['wiki_05', 'wiki_01', 'wiki_02', 'wiki_04', 'wiki_03', 'wiki_00', 'wiki_06', 'wiki_07', 'wiki_08']

In [ ]:
!find /usr/local/lib/python* -name "clean.py"

/usr/local/lib/python3.11/dist-packages/wikiextractor/clean.py
/usr/local/lib/python3.11/dist-packages/setuptools/_distutils/command/clean.py
/usr/local/lib/python3.11/dist-packages/pygments/lexers/clean.py
/usr/local/lib/python3.11/dist-packages/lxml/html/clean.py
/usr/local/lib/python3.11/dist-packages/wandb/vendor/pygments/lexers/clean.py

In [ ]:
import subprocess

subprocess.run([
    'python',
    '/usr/local/lib/python3.11/dist-packages/wikiextractor/clean.py',
    'extracted_500000/AA/wiki_00',
    '-o', '/content/cleaned_output.txt'
])

CompletedProcess(args=['python', '/usr/local/lib/python3.11/dist-packages/wikiextractor/clean.py', 'extracted_500000/AA/wiki_00', '-o', '/content/cleaned_output.txt'], returncode=0)

In [ ]:
import os
print(os.getcwd())

/content

In [ ]:
!ls -l

total 902720
drwxr-xr-x 2 root root      4096 Apr 25 09:09 extracted
drwxr-xr-x 3 root root      4096 Apr 25 08:41 extracted_100000
drwxr-xr-x 3 root root      4096 Apr 25 10:13 extracted_500000
-rw-r--r-- 1 root root  38290692 Apr 25 10:13 partial.xml
drwxr-xr-x 1 root root      4096 Apr 23 13:39 sample_data
-rw-r--r-- 1 root root 319539636 Apr 20 18:40 simplewiki-latest-pages-articles.xml.bz2
-rw-r--r-- 1 root root 319539636 Apr 20 18:40 simplewiki-latest-pages-articles.xml.bz2.1
-rw-r--r-- 1 root root 246984774 Apr 25 09:40 tawiki-latest-pages-articles.xml.bz2
drwxr-xr-x 5 root root      4096 Apr 25 10:11 wikiextractor

In [ ]:
with open('extracted_500000/AA/wiki_01', 'r') as f:
    print(f.read(10000))  # Print the first 1000 characters to check

<doc id="566" url="https://simple.wikipedia.org/wiki?curid=566" title="New York City">
New York City

New York, often called New York City (NYC), is the most populous city in the United States. It is at the southern end of the U.S. state of New York. Over 8 million people currently live in the city, and over 22 million people live in the bigger New York metropolitan area. It is the financial capital of the U.S. because it is home to the nation's stock market, Wall Street, and the One World Trade Center.
New York City is on one of the world's largest natural harbors. It is made up of five boroughs, each of which is a county of the state of New York. The five boroughs—Brooklyn, Queens, Manhattan, the Bronx, and Staten Island—were combined into one city in 1898. The city and its metropolitan area are an important place for legal immigration to the United States. As many as 800 languages are spoken in New York, making it the most linguistically diverse city in the world. New York has more than 3.2 million people born outside the United States, the biggest foreign-born population of any city in the world as of 2016.
New York City started as a trading post created by colonists from the Dutch Republic in 1624 on Lower Manhattan; the post was named New Amsterdam in 1626. In 1664, the English controlled the city and the areas around it, and were renamed "New York" after King Charles II of England gave the lands to his brother, the Duke of York. New York was the capital of the United States from 1785 until 1790, and has been the biggest U.S. city since 1790. The Statue of Liberty welcomed millions of immigrants as they came to the U.S. by ship in the late 19th and early 20th centuries, and it is a symbol of the U.S. and its ideals of liberty and peace. In the 21st century, New York has grew into a global hub of creativity and entrepreneurship and environmental sustainability, and as a symbol of freedom and cultural diversity. In 2019, New York was voted the best city in the world in a survey of over 30,000 people from 48 cities worldwide, because of its cultural diversity.
Many districts and landmarks in New York City are well known, including three of the world's ten most visited tourist places in 2013. A record 62.8 million tourists came to New York City in 2017. Times Square is the colorful area of the Broadway Theater District, one of the world's busiest pedestrian intersections, and a famous area for the world's entertainment industry. Many of the city's landmarks, skyscrapers, and parks are known around the world. Manhattan's real estate market is one of the most expensive in the world. New York has more Chinese people outside of China than anywhere in the world, with many Chinatowns across the city. The New York City Subway is the biggest single-operator rapid transit system worldwide, with rail stations. The city has over 120 colleges and universities, including Columbia University, New York University, Rockefeller University, and the City University of New York system, which is the biggest urban public university system in the United States. The world's two largest stock exchanges, the New York Stock Exchange, located on Wall Street in the Financial District of Lower Manhattan, and NASDAQ, headquartered in Midtown Manhattan, are both in Manhattan. New York have started from Enbuilting Tower and Grattacielis in nome of Frank Greco, from 1945 and Togni's 1948, and with magyas of Robertson, after 1981.
History.
Name.
In 1664, the city was named after the Duke of York, who would become King James II of England. James's older brother, King Charles II, had chosen the Duke proprietor of the former territory of New Netherland, including the city of New Amsterdam, which England had recently taken from the Dutch.
Early history.
The oldest part of the city, the island of Manhattan, still has its original Lenape name. Although Native people such as the Lenape and Canaries had lived there for many thousands of years, New York City was first explored by Europeans in the 1500s. When Florentine explorer Giovanni da Verrazzano found the entrance to New York Harbor in the year 1524, he gave to this site the name of New Angoulême in the honor of Francois 1st. In 1609, the English explorer Henry Hudson rediscovered New York Harbor while looking for the Northwest Passage to the Orient for the Dutch East India Company. Hudson's first mate said it was "a very good Harbour for all windes" and the river was "a mile broad" and "full of fish".
Juan Rodriguez (transliterated to Dutch as "Jan Rodrigues") was one of the first people associated with Europe to live there. He was a merchant from Santo Domingo. He was born in Santo Domingo of Portuguese and African descent, and he came to Manhattan during the winter of 1613–14. He trapped for pelts and traded with the local people as a representative of the Dutch. Broadway, from 159th Street to 218th Street in Upper Manhattan, is named Juan Rodriguez Way in his honor.
Dutch control.
New York City was settled by Europeans from The Netherlands in 1624. The Dutch called the whole area of New York Netherland (New Netherland) and they named a fort and town on the south end of Brooklyn.
In 1626, the Dutch colonial Director-General Peter Minuit, acting for the Dutch West India Company, bought the island of Manhattan from the "Canarsie", a small Lenape band. He paid "the value of 60 guilders" (about $900 in 2018). A false story says that Manhattan was bought for $24 worth of glass beads. 1626 was also the year the Dutch began to bring black slaves there.
After the purchase, New Amsterdam grew slowly. In 1647, Peter Stuyvesant started his job as the last Director-General of New Netherland. During this time, the number of people of New Netherland grew from 2,000 to 8,000.
Island New Amsterdam (New Amsterdam), after the capital city of the Netherlands, which was to become present-day New York. The English took over the colony in 1664 during the second Anglo-Dutch War. They changed the name to New York, to honor the Duke of York, who later became King James II of England and James VII of Scotland. The Dutch surrendered Nieuw Amsterdam without fighting.
English control.
By the time the English took New York, there were many other Dutch towns in what would become New York City, including Breukelen (Brooklyn), Vlissingen (Flushing), and Nieuw Haarlem (Harlem). There were already some English towns in the area also, such as Gravesend in Brooklyn and Newtown in Queens. Dutch, English and other people had been living together in New York for a long time.
New York became more important as a trading port while under British rule in the early 1700s. It also became a center of slavery as the British increased the slave trade and built a slave market in the city. 42% of households owned slaves by 1730, the highest percentage outside Charleston, South Carolina.
The 1735 trial and acquittal in Manhattan of John Peter Zenger, who had been accused of seditious libel after criticizing colonial governor William Cosby, helped to create the freedom of the press in North America. In 1754, Columbia University was created under charter by King George II; it was called King's College, and it was in Lower Manhattan.
American Revolution.
New York quickly grew to become a large and important port city. The Stamp Act Congress met in New York in October 1765, as the Sons of Liberty. It organized in the city, and they skirmished over the next ten years with British troops stationed there. The important Battle of Long Island of the American Revolution was fought in Brooklyn in 1776; it was the biggest battle of the war. The Americans lost the battle. The British used the area as its headquarters for the war in North America.
New York was the capital of the United States under the Articles of Confederation from 1785 to 1788. When the US Constitution was made, it stayed as the capital from 1789 until 1790. In 1789, the first President of the United States, George Washington, was inaugurated; the first United States Congress and the Supreme Court of the United States each met for the first time, and the United States Bill of Rights was written, all at Federal Hall on Wall Street. By 1790, New York grew bigger than Philadelphia, so it become the biggest city in the United States. By the end of 1790, because of the Residence Act, Philadelphia became the new capital.
Nineteenth century.
During the nineteenth century, New York City's population grew from ~60,000 to ~3.43 million. The number of black people in New York City reached more than 16,000 in 1840. Even though slavery and the slave trade were abolished in New York, the slave trade continued illegally for many years.
The Great Irish Famine brought a many Irish immigrants; more than 200,000 were living in New York by 1860, more than a quarter of the city's population. There was also many people from German provinces, and Germans made up another 25% of New York's population by 1860.
During the American Civil War, many white people in the city supported the Confederate States of America, and July 1863 they killed many black New Yorkers in a riot.
Modern history.
In 1898, the cities of New York and Brooklyn came together with the Bronx, Staten Island, and the western towns in Queens County to make Greater New York. This is the total area of the City of New York today. Around this time, many new immigrants came into New York City. They came in at Ellis Island, an island in New York's harbor near the Statue of Liberty. Many of them then moved to the Lower East Side neighborhood in Manhattan, which had over a million people living in just a few square miles.
Early in the twentieth century, with better transportation, more people moved to outer parts of the greater city, and many commuted to Manhattan. Many skyscrapers and other big buildings were put up to provide places to work.
In the 1970s, many jobs were lost due to industrial restructuring. This caused New York City to have economic p

### Method 4  
reference: https://mani2106.github.io/Blog-Posts/data-cleaning/language-model/2020/04/14/wiki-data-extraction.html

In [ ]:
# For JSON data extraction
import json
# For path manipulations
from pathlib import Path
# For preprocessing
import string
# For deleting files and folders
import shutil

# To clone necessary files
import git
# To download the dump
import requests as req
# To use wikiextractor
import subprocess
# To clean and process data
import pandas as pd

In [ ]:
from pathlib import Path

# Define working paths
DATA_PATH = Path('/content')
EXTRACTED_PATH = DATA_PATH / 'extracted'
EXTRACTED_PATH.mkdir(parents=True, exist_ok=True)

In [ ]:
# Download Wikipedia dump
bzip_file = req.get('https://dumps.wikimedia.org/tawiki/latest/tawiki-latest-pages-articles.xml.bz2')
with open(DATA_PATH / 'tawiki-latest-pages-articles.xml.bz2', 'wb') as f:
    f.write(bzip_file.content)

In [ ]:
# Clone WikiExtractor
import os

WIKIEXTRACTOR_PATH = DATA_PATH / 'wikiextractor'
if not WIKIEXTRACTOR_PATH.exists():
    git.Git(str(DATA_PATH)).clone("https://github.com/attardi/wikiextractor.git")

In [ ]:
# Run WikiExtractor with JSON output
run_stat = subprocess.run([
    'python',
    str(DATA_PATH / 'wikiextractor/WikiExtractor.py'),
    '-s', '--json',
    '-o', str(EXTRACTED_PATH),
    str(DATA_PATH / 'tawiki-latest-pages-articles.xml.bz2')
])

In [ ]:
print(run_stat.returncode)  # 0 means success

2

In [ ]:
run_stat = subprocess.run([
    'python',
    str(DATA_PATH / 'wikiextractor/wikiextractor/WikiExtractor.py'),
    '-s', '--json',
    '-o', str(EXTRACTED_PATH),
    str(DATA_PATH / 'tawiki-latest-pages-articles.xml.bz2')
], capture_output=True, text=True)

print(run_stat.stderr)

Traceback (most recent call last):
  File "/content/wikiextractor/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
ImportError: attempted relative import with no known parent package

This error means Python is trying to use a relative import, but since you're running WikiExtractor.py as a script, Python doesn't recognize it as part of a package.  
Instead of running the .py file directly, run the module using Python's -m flag from the parent folder of wikiextractor.

In [ ]:
import subprocess
import os

# Change to the /content/wikiextractor directory so Python treats it as a package
os.chdir('/content/wikiextractor')

# Now run the module with -m
run_stat = subprocess.run([
    'python', '-m', 'wikiextractor.WikiExtractor',
    '-s', '--json',
    '-o', str(EXTRACTED_PATH),
    str(DATA_PATH / 'tawiki-latest-pages-articles.xml.bz2')
], capture_output=True, text=True)

print(run_stat.stderr)

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/wikiextractor/wikiextractor/WikiExtractor.py", line 66, in <module>
    from .extract import Extractor, ignoreTag, define_template, acceptedNamespaces
  File "/content/wikiextractor/wikiextractor/extract.py", line 382, in <module>
    ExtLinkBracketedRegex = re.compile(
                            ^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 872, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 4

In [ ]:
# Collect all extracted files (recursively)
files_extracted = [str(f) for f in EXTRACTED_PATH.rglob("*") if f.is_file()]

In [ ]:
print((DATA_PATH / 'tawiki-latest-pages-articles.xml.bz2').exists())

True

In [ ]:
files_extracted

[]

In [ ]:
lang_text = [json.loads(line)
                for _file in files_extracted
                for line in open(_file)]

In [ ]:
lang_text

[]

In [ ]:
filter_english = lambda text: ' '.join([
    word for word in text.split()
    if word.translate(str.maketrans('', '', string.punctuation)).isalpha() is False
])

In [ ]:
# Since we have a list of dictionaries.
lang_df = pd.DataFrame(lang_text)
lang_df.head()

Empty DataFrame
Columns: []
Index: []

In [ ]:
lang_df['text'] = lang_df['text'].apply(filter_english)

# Downloading Wikipedia dumps from Kaggle:
https://www.kaggle.com/datasets/segfall/markdownlike-wikipedia-dumps-in-sqlite?select=zh.db

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json

{'kaggle (1).json': b'{"username":"fuhuafugui","key":"81cd67d5c4a236b0d07a17889cdc57bc"}'}

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.1)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d segfall/markdownlike-wikipedia-dumps-in-sqlite
# downloading all the data always fails

Dataset URL: https://www.kaggle.com/datasets/segfall/markdownlike-wikipedia-dumps-in-sqlite
License(s): CC-BY-SA-3.0
^C

In [ ]:
!kaggle datasets files segfall/markdownlike-wikipedia-dumps-in-sqlite

name                   size  creationDate
--------------  -----------  --------------------------
en.db           43240423424  2021-07-24 06:28:43.764000
enwikiquote.db    505217024  2021-07-24 06:18:20.760000
fr.db           14772948992  2021-07-24 06:22:23.756000
simple.db         975085568  2021-07-24 06:18:23.225000
zh.db            5665587200  2021-07-24 06:19:38.388000

In [ ]:
!kaggle datasets download -d segfall/markdownlike-wikipedia-dumps-in-sqlite -f en.db
# downloading only the en.db still fails

Dataset URL: https://www.kaggle.com/datasets/segfall/markdownlike-wikipedia-dumps-in-sqlite
License(s): CC-BY-SA-3.0
^C

In [ ]:
!ls -l

total 822824
-rw-r--r-- 1 root root 205520896 Apr 24 09:38  cassava-leaf-disease-classification.zip
-rw-r--r-- 1 root root 317423275 Apr 24 09:26  enwiki-latest-pages-articles.xml.bz2
-rwxr-xr-x 1 root root       799 Apr 24 09:15  extract.sh
-rw-r--r-- 1 root root        66 Apr 24 09:47 'kaggle (1).json'
-rw-r--r-- 1 root root        66 Apr 24 09:36  kaggle.json
-rw-r--r-- 1 root root     34523 Apr 24 09:15  LICENSE
-rw-r--r-- 1 root root     13798 Apr 23 03:15  procurement-strategy-dataset-for-kraljic-matrix.zip
-rw-r--r-- 1 root root      6621 Apr 24 09:15  README.md
-rw-r--r-- 1 root root      1321 Apr 24 09:15  setup.py
-rw-r--r-- 1 root root 319539636 Apr 20 18:40  simplewiki-latest-pages-articles.xml.bz2
drwxr-xr-x 3 root root      4096 Apr 24 09:16  wikiextractor

In [ ]:
!unzip markdownlike-wikipedia-dumps-in-sqlite.zip

unzip:  cannot find or open markdownlike-wikipedia-dumps-in-sqlite.zip, markdownlike-wikipedia-dumps-in-sqlite.zip.zip or markdownlike-wikipedia-dumps-in-sqlite.zip.ZIP.

In [ ]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('path_to_extracted_database.db')  # Replace with the actual path to the .db file

# Example: Read a table into a pandas DataFrame
df = pd.read_sql_query("SELECT * FROM your_table_name LIMIT 5;", conn)

# Display the DataFrame
print(df.head())

# Close the connection
conn.close()

# Another try with Wikidumps

## English Wikidump

In [ ]:
!pip uninstall wikiextractor
!pip install git+https://github.com/attardi/wikiextractor.git@ab8988ebfa9e4557411f3d4c0f4ccda139e18875

WARNING: Skipping wikiextractor as it is not installed.
Collecting git+https://github.com/attardi/wikiextractor.git@ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Cloning https://github.com/attardi/wikiextractor.git (to revision ab8988ebfa9e4557411f3d4c0f4ccda139e18875) to /tmp/pip-req-build-trh36lj1
  Running command git clone --filter=blob:none --quiet https://github.com/attardi/wikiextractor.git /tmp/pip-req-build-trh36lj1
  Running command git rev-parse -q --verify 'sha^ab8988ebfa9e4557411f3d4c0f4ccda139e18875'
  Running command git fetch -q https://github.com/attardi/wikiextractor.git ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Running command git checkout -q ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Resolved https://github.com/attardi/wikiextractor.git to commit ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wikiextractor
  Building wheel for wikiextractor (setup.py) ... done
  Created wheel for wikiextractor: filename=wikiextractor-3.0.7-py3-none-any.whl size=47605 sha256=34c03633997a5ebdd0fa1efc9fa8c945d18333137777c0682927640f93caaa53
  Stored in directory: /root/.cache/pip/wheels/aa/7c/fa/5d3adccb0fc93c22d5710082a349928c889caa4aaf8f1a3112
Successfully built wikiextractor
Installing collected packages: wikiextractor
Successfully installed wikiextractor-3.0.7

In [ ]:
!wget https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2

--2025-04-25 17:39:50--  https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2
Resolving dumps.wikimedia.org (dumps.wikimedia.org)... 208.80.154.71, 2620:0:861:3:208:80:154:71
Connecting to dumps.wikimedia.org (dumps.wikimedia.org)|208.80.154.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23841932900 (22G) [application/octet-stream]
Saving to: ‘enwiki-latest-pages-articles.xml.bz2’

enwiki-latest-pages 100%[===================>]  22.20G  4.14MB/s    in 91m 30s

2025-04-25 19:11:21 (4.14 MB/s) - ‘enwiki-latest-pages-articles.xml.bz2’ saved [23841932900/23841932900]

This has to be donloaded completely. otherwise ERROR:  
 (EOFError: Compressed file ended before the end-of-stream marker was reached) typically occurs when the .bz2 file is corrupted or not completely downloaded. It suggests that the file is incomplete, and the decompression process is encountering an unexpected end.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!mkdir -p /content/drive/MyDrive/wikipedia_dumps
!mv /content/enwiki-latest-pages-articles.xml.bz2 /content/drive/MyDrive/wikipedia_dumps/

In [ ]:
!find /content -name "enwiki-latest-pages-articles.xml.bz2"

/content/drive/MyDrive/wikipedia_dumps/enwiki-latest-pages-articles.xml.bz2

In [ ]:
!bzcat /content/drive/MyDrive/wikipedia_dumps/enwiki-latest-pages-articles.xml.bz2 | head -n 1000000 > partial.xml

In [ ]:
!python -m wikiextractor.WikiExtractor partial.xml --output extracted

INFO: Preprocessing 'partial.xml' to collect template definitions: this may take some time.
INFO: Loaded 0 templates in 1.1s
INFO: Starting page extraction from partial.xml.
INFO: Using 1 extract processes.
INFO: Finished 1-process extraction of 3779 articles in 36.6s (103.2 art/s)

In [ ]:
extracted_dir = 'extracted/AA'

# List all files and subdirectories in the directory
files_and_subdirs = os.listdir(extracted_dir)

print(files_and_subdirs)

['wiki_43', 'wiki_12', 'wiki_42', 'wiki_07', 'wiki_17', 'wiki_33', 'wiki_48', 'wiki_31', 'wiki_08', 'wiki_53', 'wiki_01', 'wiki_04', 'wiki_30', 'wiki_35', 'wiki_40', 'wiki_23', 'wiki_15', 'wiki_13', 'wiki_36', 'wiki_25', 'wiki_52', 'wiki_29', 'wiki_39', 'wiki_47', 'wiki_37', 'wiki_22', 'wiki_00', 'wiki_49', 'wiki_05', 'wiki_28', 'wiki_44', 'wiki_16', 'wiki_18', 'wiki_54', 'wiki_46', 'wiki_19', 'wiki_50', 'wiki_02', 'wiki_41', 'wiki_20', 'wiki_11', 'wiki_32', 'wiki_51', 'wiki_27', 'wiki_24', 'wiki_21', 'wiki_45', 'wiki_34', 'wiki_26', 'wiki_38', 'wiki_10', 'wiki_09', 'wiki_06', 'wiki_03', 'wiki_14']

In [ ]:
!find . -type f -name "wiki_*"

./drive/MyDrive/wiki_extracted/extracted/AA/wiki_12
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_07
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_17
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_08
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_01
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_04
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_23
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_15
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_13
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_25
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_22
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_00
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_05
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_16
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_18
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_19
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_02
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_20
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_11
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_27
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_24
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_21
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_26
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_10
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_09
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_06
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_03
./drive/MyDrive/wiki_extracted/extracted/AA/wiki_14
./extracted/AA/wiki_43
./extracted/AA/wiki_12
./extracted/AA/wiki_42
./extracted/AA/wiki_07
./extracted/AA/wiki_17
./extracted/AA/wiki_33
./extracted/AA/wiki_48
./extracted/AA/wiki_31
./extracted/AA/wiki_08
./extracted/AA/wiki_53
./extracted/AA/wiki_01
./extracted/AA/wiki_04
./extracted/AA/wiki_30
./extracted/AA/wiki_35
./extracted/AA/wiki_40
./extracted/AA/wiki_23
./extracted/AA/wiki_15
./extracted/AA/wiki_13
./extracted/AA/wiki_36
./extracted/AA/wiki_25
./extracted/AA/wiki_52
./extracted/AA/wiki_29
./extracted/AA/wiki_39
./extracted/AA/wiki_47
./extracted/AA/wiki_37
./extracted/AA/wiki_22
./extracted/AA/wiki_00
./extracted/AA/wiki_49
./extracted/AA/wiki_05
./extracted/AA/wiki_28
./extracted/AA/wiki_44
./extracted/AA/wiki_16
./extracted/AA/wiki_18
./extracted/AA/wiki_54
./extracted/AA/wiki_46
./extracted/AA/wiki_19
./extracted/AA/wiki_50
./extracted/AA/wiki_02
./extracted/AA/wiki_41
./extracted/AA/wiki_20
./extracted/AA/wiki_11
./extracted/AA/wiki_32
./extracted/AA/wiki_51
./extracted/AA/wiki_27
./extracted/AA/wiki_24
./extracted/AA/wiki_21
./extracted/AA/wiki_45
./extracted/AA/wiki_34
./extracted/AA/wiki_26
./extracted/AA/wiki_38
./extracted/AA/wiki_10
./extracted/AA/wiki_09
./extracted/AA/wiki_06
./extracted/AA/wiki_03
./extracted/AA/wiki_14

In [ ]:
with open('extracted/AA/wiki_00', 'r') as f:
    print(f.read(10000))  # Print the first 1000 characters to check

<doc id="10" url="https://en.wikipedia.org/wiki?curid=10" title="AccessibleComputing">
AccessibleComputing



</doc>
<doc id="12" url="https://en.wikipedia.org/wiki?curid=12" title="Anarchism">
Anarchism

Anarchism is a political philosophy and movement that seeks to abolish all institutions that perpetuate authority, coercion, or hierarchy, primarily targeting the state and capitalism. Anarchism advocates for the replacement of the state with stateless societies and voluntary free associations. A historically left-wing movement, anarchism is usually described as the libertarian wing of the socialist movement (libertarian socialism).
Although traces of anarchist ideas are found all throughout history, modern anarchism emerged from the Enlightenment. During the latter half of the 19th and the first decades of the 20th century, the anarchist movement flourished in most parts of the world and had a significant role in workers' struggles for emancipation. Various anarchist schools of thought formed during this period. Anarchists have taken part in several revolutions, most notably in the Paris Commune, the Russian Civil War and the Spanish Civil War, whose end marked the end of the classical era of anarchism. In the last decades of the 20th and into the 21st century, the anarchist movement has been resurgent once more, growing in popularity and influence within anti-capitalist, anti-war and anti-globalisation movements.
Anarchists employ diverse approaches, which may be generally divided into revolutionary and evolutionary strategies; there is significant overlap between the two. Evolutionary methods try to simulate what an anarchist society might be like, but revolutionary tactics, which have historically taken a violent turn, aim to overthrow authority and the state. Many facets of human civilization have been influenced by anarchist theory, critique, and praxis.
Etymology, terminology, and definition.
The etymological origin of "anarchism" is from the Ancient Greek "anarkhia" (ἀναρχία), meaning "without a ruler", composed of the prefix "an-" ("without") and the word "arkhos" ("leader" or "ruler"). The suffix "-ism" denotes the ideological current that favours anarchy. "Anarchism" appears in English from 1642 as "anarchisme" and "anarchy" from 1539; early English usages emphasised a sense of disorder. Various factions within the French Revolution labelled their opponents as "anarchists", although few such accused shared many views with later anarchists. Many revolutionaries of the 19th century such as William Godwin (1756–1836) and Wilhelm Weitling (1808–1871) would contribute to the anarchist doctrines of the next generation but did not use "anarchist" or "anarchism" in describing themselves or their beliefs.
The first political philosopher to call himself an "anarchist" () was Pierre-Joseph Proudhon (1809–1865), marking the formal birth of anarchism in the mid-19th century. Since the 1890s and beginning in France, "libertarianism" has often been used as a synonym for anarchism; its use as a synonym is still common outside the United States. Some usages of "libertarianism" refer to individualistic free-market philosophy only, and free-market anarchism in particular is termed "libertarian anarchism".
While the term "libertarian" has been largely synonymous with anarchism, its meaning has more recently been diluted by wider adoption from ideologically disparate groups, including both the New Left and libertarian Marxists, who do not associate themselves with authoritarian socialists or a vanguard party, and extreme cultural liberals, who are primarily concerned with civil liberties. Additionally, some anarchists use "libertarian socialist" to avoid anarchism's negative connotations and emphasise its connections with socialism. "Anarchism" is broadly used to describe the anti-authoritarian wing of the socialist movement. Anarchism is contrasted to socialist forms which are state-oriented or from above. Scholars of anarchism generally highlight anarchism's socialist credentials and criticise attempts at creating dichotomies between the two. Some scholars describe anarchism as having many influences from liberalism, and being both liberal and socialist but more so. Many scholars reject anarcho-capitalism as a misunderstanding of anarchist principles.
While opposition to the state is central to anarchist thought, defining "anarchism" is not an easy task for scholars, as there is a lot of discussion among scholars and anarchists on the matter, and various currents perceive anarchism slightly differently. Major definitional elements include the will for a non-coercive society, the rejection of the state apparatus, the belief that human nature allows humans to exist in or progress toward such a non-coercive society, and a suggestion on how to act to pursue the ideal of anarchy.
History.
Pre-modern era.
The most notable precursors to anarchism in the ancient world were in China and Greece. In China, philosophical anarchism (the discussion on the legitimacy of the state) was delineated by Taoist philosophers Zhuang Zhou and Laozi. Alongside Stoicism, Taoism has been said to have had "significant anticipations" of anarchism.
Anarchic attitudes were also articulated by tragedians and philosophers in Greece. Aeschylus and Sophocles used the myth of Antigone to illustrate the conflict between laws imposed by the state and personal autonomy. Socrates questioned Athenian authorities constantly and insisted on the right of individual freedom of conscience. Cynics dismissed human law ("nomos") and associated authorities while trying to live according to nature ("physis"). Stoics were supportive of a society based on unofficial and friendly relations among its citizens without the presence of a state.
In medieval Europe, there was no anarchistic activity except some ascetic religious movements. These, and other Muslim movements, later gave birth to religious anarchism. In the Sasanian Empire, Mazdak called for an egalitarian society and the abolition of monarchy, only to be soon executed by Emperor Kavad I. In Basra, religious sects preached against the state. In Europe, various religious sects developed anti-state and libertarian tendencies.
Renewed interest in antiquity during the Renaissance and in private judgment during the Reformation restored elements of anti-authoritarian secularism in Europe, particularly in France. Enlightenment challenges to intellectual authority (secular and religious) and the revolutions of the 1790s and 1848 all spurred the ideological development of what became the era of classical anarchism.
Modern era.
During the French Revolution, partisan groups such as the Enragés and the saw a turning point in the fermentation of anti-state and federalist sentiments. The first anarchist currents developed throughout the 18th century as William Godwin espoused philosophical anarchism in England, morally delegitimising the state, Max Stirner's thinking paved the way to individualism and Pierre-Joseph Proudhon's theory of mutualism found fertile soil in France. By the late 1870s, various anarchist schools of thought had become well-defined and a wave of then-unprecedented globalisation occurred from 1880 to 1914. This era of classical anarchism lasted until the end of the Spanish Civil War and is considered the golden age of anarchism.
Drawing from mutualism, Mikhail Bakunin founded collectivist anarchism and entered the International Workingmen's Association, a class worker union later known as the First International that formed in 1864 to unite diverse revolutionary currents. The International became a significant political force, with Karl Marx being a leading figure and a member of its General Council. Bakunin's faction (the Jura Federation) and Proudhon's followers (the mutualists) opposed state socialism, advocating political abstentionism and small property holdings. After bitter disputes, the Bakuninists were expelled from the International by the Marxists at the 1872 Hague Congress. Anarchists were treated similarly in the Second International, being ultimately expelled in 1896. Bakunin predicted that if revolutionaries gained power by Marx's terms, they would end up the new tyrants of workers. In response to their expulsion from the First International, anarchists formed the St. Imier International. Under the influence of Peter Kropotkin, a Russian philosopher and scientist, anarcho-communism overlapped with collectivism. Anarcho-communists, who drew inspiration from the 1871 Paris Commune, advocated for free federation and for the distribution of goods according to one's needs.
By the turn of the 20th century, anarchism had spread all over the world. It was a notable feature of the international syndicalist movement. In China, small groups of students imported the humanistic pro-science version of anarcho-communism. Tokyo was a hotspot for rebellious youth from East Asian countries, who moved to the Japanese capital to study. In Latin America, Argentina was a stronghold for anarcho-syndicalism, where it became the most prominent left-wing ideology. During this time, a minority of anarchists adopted tactics of revolutionary political violence, known as propaganda of the deed. The dismemberment of the French socialist movement into many groups and the execution and exile of many Communards to penal colonies following the suppression of the Paris Commune favoured individualist political expression and acts. Even though many anarchists distanced themselves from these terrorist acts, infamy came upon the movement and attempts were made to prevent anarchists immigrating to the US, including the Immigration Act of 1903, also called the Anarchist Exclusion Act. Illegalism was another strategy which some anarchists adopted during this period.
Despite concerns, anarchists enthusiastically participated in the Russian Revolution in opposition to the White movement, especially in the Makhnovshchina; however, th

In [ ]:
import os
import shutil

# Source base directory
source_dir = "/content"
# Target base directory in Google Drive
target_dir = "/content/drive/MyDrive/wiki_extracted"

# Create target dir if it doesn't exist
os.makedirs(target_dir, exist_ok=True)

# Look for folders that likely contain extracted wiki content
for folder_name in os.listdir(source_dir):
    full_path = os.path.join(source_dir, folder_name)
    if os.path.isdir(full_path) and (
        folder_name.startswith("extracted") or folder_name == "text"
    ):
        target_path = os.path.join(target_dir, folder_name)
        print(f"Moving {full_path} -> {target_path}")
        shutil.move(full_path, target_path)

print("✅ All extracted folders moved to Google Drive.")

Moving /content/extracted -> /content/drive/MyDrive/wiki_extracted/extracted
✅ All extracted folders moved to Google Drive.

Custom Category Dumps (Creating Your Own)
If you need to create a custom category dump for a specific set of categories (like articles related to "Physics", "Technology", or any other topics), you would need to:

Download the full Wikipedia dump.
Use a tool like WikiExtractor to extract the relevant data.
Use regular expressions, filtering scripts, or XPath queries to filter and select the category you’re interested in.

the doc id (e.g., <doc id="316" ...>) is not the same across different language versions of Wikipedia. The doc id is a unique identifier specific to the extracted data from each language's Wikipedia dump.  
How to Match the Same Article Across Languages:
To match the same article across different languages, you will need to rely on a more reliable identifier, such as:

Titles: You can compare the titles across languages. Articles that share the same or very similar titles are likely to be the same article in different languages (e.g., "Academy Award for Best Production Design" in English, "Academy Award für Beste Szenenbild" in German).
Wikidata IDs: The most reliable way to match the same article across different languages is by using Wikidata IDs. Every article on Wikipedia is linked to a unique Wikidata entry, which has the same ID across all language versions of the article. For example, the article about the "Academy Award for Best Production Design" would have a corresponding Wikidata ID that can be used to locate the same article in different languages.
How to Use Wikidata for Cross-Language Matching:
You can fetch the Wikidata ID for each article. If you have the article title, you can search for the corresponding Wikidata page.
Once you have the Wikidata ID, you can retrieve the corresponding article in different languages using that ID, as all language versions of a Wikipedia article point to the same Wikidata page.

## German Wikidump

In [ ]:
!pip install git+https://github.com/attardi/wikiextractor.git@ab8988ebfa9e4557411f3d4c0f4ccda139e18875

Collecting git+https://github.com/attardi/wikiextractor.git@ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Cloning https://github.com/attardi/wikiextractor.git (to revision ab8988ebfa9e4557411f3d4c0f4ccda139e18875) to /tmp/pip-req-build-c_eee6ae
  Running command git clone --filter=blob:none --quiet https://github.com/attardi/wikiextractor.git /tmp/pip-req-build-c_eee6ae
  Running command git rev-parse -q --verify 'sha^ab8988ebfa9e4557411f3d4c0f4ccda139e18875'
  Running command git fetch -q https://github.com/attardi/wikiextractor.git ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Running command git checkout -q ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Resolved https://github.com/attardi/wikiextractor.git to commit ab8988ebfa9e4557411f3d4c0f4ccda139e18875
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wikiextractor
  Building wheel for wikiextractor (setup.py) ... done
  Created wheel for wikiextractor: filename=wikiextractor-3.0.7-py3-none-any.whl size=47605 sha256=e17c7c7b7841e707e4a62f215a6aa993cc5c46aea00fbe0da53e1bccd696f711
  Stored in directory: /root/.cache/pip/wheels/aa/7c/fa/5d3adccb0fc93c22d5710082a349928c889caa4aaf8f1a3112
Successfully built wikiextractor
Installing collected packages: wikiextractor
Successfully installed wikiextractor-3.0.7

In [ ]:
!wget https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2

--2025-04-28 19:16:52--  https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2
Resolving dumps.wikimedia.org (dumps.wikimedia.org)... 208.80.154.71, 2620:0:861:3:208:80:154:71
Connecting to dumps.wikimedia.org (dumps.wikimedia.org)|208.80.154.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7474538699 (7.0G) [application/octet-stream]
Saving to: ‘dewiki-latest-pages-articles.xml.bz2’

dewiki-latest-pages 100%[===================>]   6.96G  4.04MB/s    in 28m 22s

2025-04-28 19:45:15 (4.19 MB/s) - ‘dewiki-latest-pages-articles.xml.bz2’ saved [7474538699/7474538699]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!mkdir -p /content/drive/MyDrive/de_wikipedia_dumps
!mv /content/dewiki-latest-pages-articles.xml.bz2 /content/drive/MyDrive/de_wikipedia_dumps/

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!bzcat /content/drive/MyDrive/de_wikipedia_dumps/dewiki-latest-pages-articles.xml.bz2 | head -n 1000000 > de_partial.xml

In [ ]:
!python -m wikiextractor.WikiExtractor de_partial.xml --output de_extracted

INFO: Preprocessing 'de_partial.xml' to collect template definitions: this may take some time.
INFO: Loaded 0 templates in 3.1s
INFO: Starting page extraction from de_partial.xml.
INFO: Using 1 extract processes.
INFO: Finished 1-process extraction of 3726 articles in 38.3s (97.4 art/s)

In [ ]:
with open('de_extracted/AA/wiki_00', 'r') as f:
    print(f.read(10000))

<doc id="1" url="https://de.wikipedia.org/wiki?curid=1" title="Alan Smithee">
Alan Smithee

Alan Smithee steht als Pseudonym für einen fiktiven Regisseur, der Filme verantwortet, bei denen der eigentliche Regisseur seinen Namen nicht mit dem Werk in Verbindung gebracht haben möchte. Von 1968 bis 2000 wurde es von der Directors Guild of America (DGA) für solche Situationen empfohlen.
Alternative Schreibweisen sind unter anderem die Ursprungsvariante "Allen Smithee" sowie "Alan Smythee" und "Adam Smithee". Auch zwei teilweise asiatisch anmutende Schreibweisen "Alan Smi Thee" und "Sumishii Aran" gehören laut IMDb dazu.
Geschichte.
Entstehung.
Das Pseudonym entstand 1968 infolge der Arbeiten am Western-Film "Death of a Gunfighter" (deutscher Titel "Frank Patch – Deine Stunden sind gezählt"). Regisseur Robert Totten und Hauptdarsteller Richard Widmark gerieten in einen Streit, woraufhin Don Siegel als neuer Regisseur eingesetzt wurde.
Der Film trug nach Abschluss der Arbeiten noch deutlich Tottens Handschrift, der auch mehr Drehtage als Siegel daran gearbeitet hatte, weshalb dieser die Nennung seines Namens als Regisseur ablehnte. Totten selbst lehnte aber ebenfalls ab. Als Lösung wurde "Allen Smithee" als ein möglichst einzigartiger Name gewählt.
In den zeitgenössischen Kritiken wurde der Regisseur u. a. von Roger Ebert mit den Worten gelobt:
Aufdeckung und Abkehr.
1997 kam die Parodie "An Alan Smithee Film: Burn Hollywood Burn" (deutscher Titel "Fahr zur Hölle Hollywood") in die Kinos, was das Pseudonym einem größeren Publikum bekannt machte, nicht zuletzt weil Arthur Hiller, der eigentliche Regisseur des Films, selbst seinen Namen zurückzog und analog zum Filmtitel das Pseudonym "Alan Smithee" benutzte. Der Film gilt als einer der schlechtesten Filme der 1990er Jahre und gewann fünf Goldene Himbeeren.
Der Film "Supernova" ist der erste Post-Smithee-Film, dort führte ein gewisser "Thomas Lee" alias Walter Hill die Regie.
Verwendung.
Die Verwendung dieses oder eines anderen Pseudonyms ist für Mitglieder der DGA streng reglementiert. Ein Regisseur, der für einen von ihm gedrehten Film seinen Namen nicht hergeben möchte, hat nach Sichtung des fertigen Films drei Tage Zeit, anzuzeigen, dass er ein Pseudonym verwenden möchte. Der Rat der DGA entscheidet binnen zwei Tagen über das Anliegen. Erhebt die Produktionsfirma Einspruch, entscheidet ein Komitee aus Mitgliedern der DGA und der Vereinigung der Film- und Fernsehproduzenten, ob der Regisseur ein Pseudonym angeben darf. Über die Beantragung muss der Regisseur Stillschweigen halten, ebenso darf er den fertigen Film nicht öffentlich kritisieren, wenn die DGA ihm die Verwendung eines Pseudonyms zugesteht. Ein Antrag des Regisseurs auf Pseudonymisierung kann abgelehnt werden, so durfte Tony Kaye den Namen Smithee bei dem Film "American History X" nicht einsetzen, obwohl er den Antrag stellte.
Auch bei nicht-US-amerikanischen Produktionen wird der Name verwendet, wie etwa beim Pilotfilm der Fernsehserie "Schulmädchen". 2007 sendete die ARD am 8. und 9. August den zweiteiligen TV-Film "Paparazzo". Auch in diesem Werk erscheint anstatt des eigentlichen Regisseurs Stephan Wagner Alan Smithee im Abspann.
Regisseure, die das Pseudonym benutzt haben:
Der Pilotfilm der Serie "MacGyver" und die fünfte Folge der ersten Staffel führen einen Alan Smithee als Regisseur. Auf der TV-Serien-Seite "TV Rage" wird Jerrold Freedman als Regisseur des Pilotfilms angegeben. Der Regisseur der fünften Folge ist unbekannt.
Zu den Drehbuchautoren, die das Pseudonym benutzt haben, gehören Sam Raimi und Ivan Raimi, die das Drehbuch zu "Die total beknackte Nuß" als "Alan Smithee, Jr." und "Alan Smithee, Sr." schrieben.
Auch in Computerspielen wird dieses Pseudonym angegeben: Im Abspann des Ego-Shooters "Marine Sharpshooter IV" aus dem Jahr 2008 wird als Art Director des Spiels "Alan Smithee" genannt.
2014 produzierte die New Yorker Performance-Kompanie Big Dance Theater "Alan Smithee Directed this Play", das im August des Jahres auch in Berlin bei Tanz im August aufgeführt wurde.

</doc>
<doc id="3" url="https://de.wikipedia.org/wiki?curid=3" title="Actinium">
Actinium

Actinium ist ein radioaktives chemisches Element mit dem Elementsymbol Ac und der Ordnungszahl 89. Im Periodensystem der Elemente steht es in der 3. IUPAC-Gruppe, der Scandiumgruppe. Das Element ist ein Metall und gehört zur 7. Periode, d-Block. Es ist der Namensgeber der Gruppe der Actinoide, der ihm folgenden 14 Elemente.
Geschichte.
Das Actinium wurde im Jahr 1899 von dem französischen Chemiker André-Louis Debierne entdeckt, der es aus Pechblende isolierte und ihm zunächst Ähnlichkeiten mit dem Titan oder dem Thorium zuschrieb; seine Bezeichnung leitete er wegen der Radioaktivität von griechisch ἀκτίς "aktís" ‚Strahl‘ ab. Friedrich Giesel entdeckte das Element unabhängig davon im Jahr 1902 und beschrieb eine Ähnlichkeit zum Lanthan; er gab ihm den Namen Emanium, eine Bildung zu lateinisch "emano" ‚ausfließen‘, ebenfalls mit Bezug zur abgegebenen Strahlung. Nachdem Actinium und Emanium im Jahre 1904 als identisch erkannt worden waren, wurde Debiernes Namensgebung der Vorzug gegeben, da er es zuerst entdeckt hatte.
Die Geschichte der Entdeckung wurde in Publikationen von 1971 und später im Jahr 2000 immer noch als fraglich beschrieben. Sie zeigen, dass die Publikationen von 1904 einerseits und die von 1899 und 1900 andererseits Widersprüche aufweisen.
Gewinnung und Darstellung.
Da in Uranerzen nur wenig Actinium vorhanden ist, spielt diese Quelle keine Rolle für die Gewinnung. Technisch wird das Isotop 227Ac durch Bestrahlung von 226Ra mit Neutronen in Kernreaktoren hergestellt.
formula_1
Die Zeitangaben sind Halbwertszeiten.
Durch den schnellen Zerfall des Actiniums waren stets nur geringe Mengen verfügbar. Die erste künstliche Herstellung von Actinium wurde im Argonne National Laboratory in Chicago durchgeführt.
Eigenschaften.
Physikalische Eigenschaften.
Das Metall ist silberweiß glänzend und relativ weich. Aufgrund seiner starken Radioaktivität leuchtet Actinium im Dunkeln in einem hellblauen Licht.
Actinium ist das namensgebende Element der Actinoiden, ähnlich wie Lanthan für die Lanthanoiden. Die Gruppe der Elemente zeigt deutlichere Unterschiede als die Lanthanoide; daher dauerte es bis 1945, bis Glenn T. Seaborg die wichtigsten Änderungen zum Periodensystem von Mendelejew vorschlagen konnte: die Einführung der Actinoide.
Chemische Eigenschaften.
Es ist sehr reaktionsfähig und wird von Luft und Wasser angegriffen, überzieht sich aber mit einer Schicht von Actiniumoxid, wodurch es vor weiterer Oxidation geschützt ist. Das Ac3+-Ion ist farblos. Das chemische Verhalten von Actinium ähnelt sehr dem Lanthan. Actinium ist in allen zehn bekannten Verbindungen dreiwertig.
Isotope.
Bekannt sind 26 Isotope, wovon nur zwei natürlich vorkommen. Das langlebigste Isotop 227Ac (Halbwertszeit 21,8 Jahre) hat zwei Zerfallskanäle: es ist ein Alpha- und Betastrahler. 227Ac ist ein Zerfallsprodukt des Uranisotops 235U und kommt zu einem kleinen Teil in Uranerzen vor. Daraus lassen sich wägbare Mengen 227Ac gewinnen, die somit ein verhältnismäßig einfaches Studium dieses Elementes ermöglichen. Da sich unter den radioaktiven Zerfallsprodukten einige Gammastrahler befinden, sind aber aufwändige Strahlenschutzvorkehrungen nötig.
Verwendung.
Actinium wird zur Erzeugung von Neutronen eingesetzt, die bei Aktivierungsanalysen eine Rolle spielen. Außerdem wird es für die thermoionische Energieumwandlung genutzt.
Beim dualen Zerfall des 227Ac geht der größte Teil unter Emission von Beta-Teilchen in das Thoriumisotop 227Th, aber ca. 1 % zerfällt durch Alpha-Emission zu Francium 223Fr. Eine Lösung von 227Ac ist daher als Quelle für das kurzlebige 223Fr verwendbar. Letzteres kann dann regelmäßig abgetrennt und untersucht werden.
Sicherheitshinweise.
Einstufungen nach der CLP-Verordnung liegen nicht vor, weil diese nur die chemische Gefährlichkeit umfassen und eine völlig untergeordnete Rolle gegenüber den auf der Radioaktivität beruhenden Gefahren spielen. Auch Letzteres gilt nur, wenn es sich um eine dafür relevante Stoffmenge handelt.
Verbindungen.
Nur eine geringe Anzahl von Actiniumverbindungen ist bekannt. Mit Ausnahme von AcPO4 sind sie alle den entsprechenden Lanthanverbindungen ähnlich und enthalten Actinium in der Oxidationsstufe +3. Insbesondere unterscheiden sich die Gitterkonstanten der jeweiligen Lanthan- und Actinium-Verbindungen nur in wenigen Prozent.
Oxide.
Actinium(III)-oxid (Ac2O3) kann durch Erhitzen des Hydroxids bei 500 °C oder des Oxalats bei 1100 °C im Vakuum erhalten werden. Das Kristallgitter ist isotyp mit den Oxiden der meisten dreiwertigen Seltenerdmetalle.
Halogenide.
Actinium(III)-fluorid (AcF3) kann entweder in Lösung oder durch Feststoffreaktion dargestellt werden. Im ersten Fall gibt man bei Raumtemperatur Flusssäure zu einer Ac3+-Lösung und fällt das Produkt aus. im anderen Fall wird Actinium-Metall mit Fluorwasserstoff bei 700 °C in einer Platinapparatur behandelt.
Actinium(III)-chlorid (AcCl3) wird durch Umsetzung von Actiniumhydroxid oder -oxalat mit Tetrachlormethan bei Temperaturen oberhalb von 960 °C erhalten.
Die Reaktion von Aluminiumbromid und Actinium(III)-oxid führt zum Actinium(III)-bromid (AcBr3) und Behandlung mit feuchtem Ammoniak bei 500 °C führt zum Oxibromid AcOBr.
Weitere Verbindungen.
Gibt man Natriumdihydrogenphosphat (NaH2PO4) zu einer Lösung von Actinium in Salzsäure, erhält man weiß gefärbtes Actiniumphosphat (AcPO4 · 0,5 H2O); ein Erhitzen von Actinium(III)-oxalat mit Schwefelwasserstoff bei 1400 °C für ein paar Minuten führt zu schwarzem Actinium(III)-sulfid (Ac2S3).

</doc>
<doc id="5" url="https://de.wikipedia.org/wiki?curid=5" title="Ang Lee">
Ang Lee

Ang Lee (; * 23. Oktober 1954 in Chaozhou, Landkreis Pingtung, Taiwan) ist ein taiwanischer Filmregisseur, Drehbuchautor und Produzent. Er ist als vielfach ausgezeichneter Regisseur bekannt für so unterschiedliche Filme wie "Eat Drink Man Woman"

# Wikidump + API (test with only 5 entries)

### Step 1: fetch QID and titels

In [ ]:
import requests
import bz2
import json

url = "https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.json.bz2"
response = requests.get(url, stream=True)

decompressed = bz2.BZ2Decompressor()
lang_keys = ['enwiki', 'dewiki', 'eswiki', 'zhwiki', 'hiwiki']
count = 0
buffer = b""

for chunk in response.iter_content(4096):
    buffer += decompressed.decompress(chunk)

    # Split by lines only when the entire chunk has been processed
    while b"\n" in buffer:
        line, buffer = buffer.split(b"\n", 1)
        try:
            line = line.decode("utf-8").strip().rstrip(',')
            if line.startswith('{'):
                obj = json.loads(line)
                sitelinks = obj.get("sitelinks", {})
                if all(lang in sitelinks for lang in lang_keys):
                    print({
                        "qid": obj["id"],
                        **{lang: sitelinks[lang]["title"] for lang in lang_keys}
                    })
                    count += 1
                    if count >= 5:
                        print("Reached 5 articles. Stopping.")
                        break  # Exit the while loop
        except Exception:
            continue

    if count >= 5:
        break

print(f"Processed {count} articles.")

{'qid': 'Q31', 'enwiki': 'Belgium', 'dewiki': 'Belgien', 'eswiki': 'Bélgica', 'zhwiki': '比利时', 'hiwiki': 'बेल्जियम'}
{'qid': 'Q8', 'enwiki': 'Happiness', 'dewiki': 'Glück', 'eswiki': 'Felicidad', 'zhwiki': '幸福', 'hiwiki': 'प्रसन्नता'}
{'qid': 'Q23', 'enwiki': 'George Washington', 'dewiki': 'George Washington', 'eswiki': 'George Washington', 'zhwiki': '乔治·华盛顿', 'hiwiki': 'जॉर्ज वॉशिंगटन'}
{'qid': 'Q2013', 'enwiki': 'Wikidata', 'dewiki': 'Wikidata', 'eswiki': 'Wikidata', 'zhwiki': '维基数据', 'hiwiki': 'विकिडेटा'}
{'qid': 'Q45', 'enwiki': 'Portugal', 'dewiki': 'Portugal', 'eswiki': 'Portugal', 'zhwiki': '葡萄牙', 'hiwiki': 'पुर्तगाल'}
Reached 5 articles. Stopping.
Processed 5 articles.

### Step 2: extract articels based on QID and titels

In [ ]:
import requests
import time

# Your sample data
entities = [
    {'qid': 'Q31', 'enwiki': 'Belgium', 'dewiki': 'Belgien', 'eswiki': 'Bélgica', 'zhwiki': '比利时', 'hiwiki': 'बेल्जियम'},
    {'qid': 'Q8', 'enwiki': 'Happiness', 'dewiki': 'Glück', 'eswiki': 'Felicidad', 'zhwiki': '幸福', 'hiwiki': 'प्रसन्नता'},
    {'qid': 'Q23', 'enwiki': 'George Washington', 'dewiki': 'George Washington', 'eswiki': 'George Washington', 'zhwiki': '乔治·华盛顿', 'hiwiki': 'जॉर्ज वॉशिंगटन'},
    {'qid': 'Q2013', 'enwiki': 'Wikidata', 'dewiki': 'Wikidata', 'eswiki': 'Wikidata', 'zhwiki': '维基数据', 'hiwiki': 'विकिडेटा'},
    {'qid': 'Q45', 'enwiki': 'Portugal', 'dewiki': 'Portugal', 'eswiki': 'Portugal', 'zhwiki': '葡萄牙', 'hiwiki': 'पुर्तगाल'}
]

# Function to fetch article extract
def fetch_extract(lang_code, title):
    url = f"https://{lang_code}.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "prop": "extracts",
        "format": "json",
        "titles": title,
        "explaintext": 1
    }
    try:
        response = requests.get(url, params=params)
        response.raise_for_status()
        data = response.json()
        page = next(iter(data["query"]["pages"].values()))
        return page.get("extract", "No extract found.")
    except Exception as e:
        return f"Error fetching: {e}"

# Loop through entities and fetch extracts
for entity in entities:
    print(f"\n=== {entity['qid']} ===")
    for lang_key in ['enwiki', 'dewiki', 'eswiki', 'zhwiki', 'hiwiki']:
        lang_code = lang_key[:2]  # 'enwiki' -> 'en'
        title = entity[lang_key]
        print(f"\n[{lang_code.upper()}] {title}")
        extract = fetch_extract(lang_code, title)
        print(extract[:500], "..." if len(extract) > 500 else "")  # limit output
        time.sleep(1.5)  # ✅ Add delay to prevent 429 Client Error

=== Q31 ===

[EN] Belgium
Belgium, officially the Kingdom of Belgium, is a country in Northwestern Europe. Situated in a coastal lowland region known as the Low Countries, it is bordered by the Netherlands to the north, Germany to the east, Luxembourg to the southeast, France to the south, and the North Sea to the west. Belgium covers an area of 30,689 km2 (11,849 sq mi) and has a population of more than 11.8 million; its population density of 383/km2 (990/sq mi) ranks 22nd in the world and sixth in Europe. The capital a ...

[DE] Belgien
Belgien (amtlich Königreich Belgien, niederländisch , französisch Royaume de Belgique) ist ein föderaler Staat in Westeuropa. Es liegt zwischen der Nordsee und den Ardennen und grenzt an die Niederlande, Deutschland, Luxemburg und Frankreich. Belgien zählte am 1. Januar 2024 rund 11,8 Millionen Einwohner auf einer Fläche von 30.688 Quadratkilometern. Mit 383 Einwohnern pro Quadratkilometer zählt Belgien zu den am dichtesten besiedelten Staaten. Der Grad der Urbanisierung Belgiens ist mit fast 98 ...

[ES] Bélgica
Bélgica (en neerlandés: ; en francés: ; en alemán: ), oficialmente Reino de Bélgica, es uno de los veintisiete Estados soberanos que forman la Unión Europea, situado en Europa noroccidental. El país cubre una superficie de 30 528 km²[1]​ y poseía en el año 2023 una población de 11 754 004 [5]​habitantes. Su capital y la conurbación más poblada es Bruselas, mientras que su ciudad (municipio) más poblada es Amberes.[6]​
Bélgica es un Estado multilingüístico con tres lenguas oficiales: el 57 % de s ...

[ZH] 比利时
比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk België；德語：Königreich Belgien），通稱比利時（法語：Belgique [bɛlʒik] （）；荷蘭語：België [ˈbɛlɣijə] （）；德語：Belgien [ˈbɛlɡi̯ən] （）），是一个位于西北欧的国家，坐落于被称之为低地国家的沿海低地地区。其领土北部与荷兰接壤，东部与德国相邻，东南毗邻卢森堡，南接法国，西濒大西洋北海。比利时的国土面积为30,689平方公里（11,849平方英里），人口超过1170万；人口密度为383平方公里（148平方英里），在全球排名第22位，在欧洲排名第七位。其首都及最大城市为布鲁塞尔；其他主要城市包括安特卫普、根特、沙勒罗瓦、列日、布魯日、那慕爾以及鲁汶。
比利时是一个实行议会制的君主立宪国家。其具有一个以地区和语言为基础构建的复杂联邦体系。全国分为三个高度自治的大区：分别为北部的弗拉芒大區、南部的瓦隆大区以及中部的布鲁塞尔首都大区。比利时还拥有两大主要语言社群，分别为讲荷蘭語的弗拉芒社群，占全国约60%的人口。以及讲法语的法语社 ...

[HI] बेल्जियम
बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर्मन: Belgien) उत्तर-पश्चिमी यूरोप में एक देश है। यह यूरोपीय संघ का संस्थापक सदस्य है और उसके मुख्यालय का मेज़बान है, साथ ही, अन्य प्रमुख अंतरराष्ट्रीय संगठनों का, जिसमें NATO भी शामिल है। 10.7 मीलियन की जनसंख्या वाले बेल्जियम का क्षेत्रफल 30,528 वर्ग किलोमीटर (11,787 वर्ग मील) है।
जर्मनिक और लैटिन यूरोप के मध्य अपनी सांस्कृतिक सीमा को विस्तृत किये हुए बेल्जियम, दो मुख्य भाषाई समूहों, फ्लेमिश और फ्रेंच-भाषी, मुख्यतः वलून्स सहित जर्मन भाषियों के एक छो ...

=== Q8 ===

[EN] Happiness
Happiness is a complex and multifaceted emotion that encompasses a range of positive feelings, from contentment to intense joy. It is often associated with positive life experiences, such as achieving goals, spending time with loved ones, or engaging in enjoyable activities. However, happiness can also arise spontaneously, without any apparent external cause.
Happiness is closely linked to well-being and overall life satisfaction. Studies have shown that individuals who experience higher levels  ...

[DE] Glück
Glück ist ein mehrdeutiger Begriff, der momentane oder auch anhaltende positive Empfindungen (Glücksgefühle) einschließt, die von stiller bis zu überschießender Art sein können. Glücklich kann man zudem eine Person nennen, der es anhaltend gut geht, weil ihr Leben viel von dem enthält, was sie als wichtig erachtet. Im Sinne des glücklichen Zufalls steht Glück für eine günstige Fügung bzw. für eine positive Schicksalswendung.
Das „Streben nach Glück“ hat als originäres individuelles Freiheitsrech ...

[ES] Felicidad
La felicidad es una emoción o estado de ánimo que experimenta un ser consciente cuando llega a un momento de conformación, bienestar o se han conseguido ciertos objetivos deseables para el individuo consciente.
Se considera que este estado de ánimo y los factores que lo condicionan son subjetivos, por lo que cada persona puede tener su propio concepto de felicidad, y con ello en mente, las razones de por qué se estaría con dicho estado de ánimo podrían estudiarse con la experimentación general:[ ...

[ZH] 幸福
幸福（古希臘語：εὐδαιμονία、拉丁語：felicitas、英語：felicity、happiness）是一种持续时间较长的心灵的满足。人类自古以来就对追求幸福的途径有着浓厚的兴趣。
研究幸福本身，及研究何种人生态度会带来幸福等等的学问，被称为“幸福学”（eudaemonics）。将幸福视为道德上的最高追求，并以能否带来幸福作为判断行为臧否之标准的思想，则被称为“幸福主义”。古典幸福主义的代表是亚里士多德，而功利主义则是近代哲学中追求幸福的典型。
自20世纪60年代以来，许多科学学科都进行着有关幸福的研究，如老人學、社会心理学、臨床研究、医学研究和快樂經濟學等。
此条目中列出哲學家、思想家、宗教家等提出的对幸福的看法及介绍最近统计调查和精神病调查与研究中的发现。


== 哲学、思想、宗教的观点 ==


=== 蘇格拉底 ===
蘇格拉底认为，人類比起“死亡”，更應該重视和正确认识“好好死亡”这一概念。


=== 亚里士多德 ===

亚里士多德在其“尼各马可伦理学”中说，幸福是所有人所追求的目标；其特征便是幸福本身即为人的终极目标，也就是说幸福不会成为实现其他目标的手段。 ...

[HI] प्रसन्नता
प्रसन्नता मानवों में पाई जाने वाली भावनाओं में सबसे सकारात्मक  भावना है। इसके होने के विभिन्न कारण हो सकते हैं:

अपनी इच्छाओं की पूर्ति से संतुष्ट होना।
अपने दिन-रात के जीवन की गतिविधियों को अपनी इच्छाओं के अनुकूल पाना।
किसी अचानक लाभ से लाभांवित होना।
किसी जटिल समस्या का समाधान प्राप्त होना।
दिन के कार्य के बाद परिजनों या दोस्तों की संगत।
किसी परिजन या मित्र की कामयाबी।
किसी मनोरंजक कार्यक्रम को दिलचस्प या मनमोहक पाना।
इन कारणों के अलावा भी कुछ लोग स्वभाव से हमेशा प्रसन्न रहने की कोशिश करते हैं ...

=== Q23 ===

[EN] George Washington
George Washington (February 22, 1732 [O.S. February 11, 1731] – December 14, 1799) was a Founding Father and the first president of the United States, serving from 1789 to 1797. As commander of the Continental Army, Washington led Patriot forces to victory in the American Revolutionary War against the British Empire. He is commonly known as the Father of His Country for his role in bringing about American independence.
Born in the Colony of Virginia, Washington became the commander of the Virgin ...

[DE] George Washington
George Washington [ˈwɒʃɪŋtən] (* 22. Februar 1732 auf dem Gutshof Wakefield (auch Pope’s Plantation genannt) im Westmoreland County, Kolonie Virginia; † 14. Dezember 1799 auf Mount Vernon, Virginia) war von 1789 bis 1797 der erste Präsident der Vereinigten Staaten von Amerika.
Als Oberbefehlshaber der Kontinentalarmee von 1775 bis 1783 war er einer der Gründerväter der USA und leitete als Vorsitzender die verfassunggebende Philadelphia Convention im Jahr 1787. Während seiner Präsidentschaft traf ...

[ES] George Washington
George Washington (Westmoreland, Virginia, América Británica, 22 de febrero de 1731-Mount Vernon, Virginia, Estados Unidos, 14 de diciembre de 1799)[1]​[2]​[3]​ fue el primer presidente de los Estados Unidos entre 1789 y 1797[4]​[5]​[6]​ y comandante en jefe del Ejército Continental revolucionario en la guerra de la Independencia de los Estados Unidos (1775-1783). En los Estados Unidos se le considera el padre de la Patria.[5]​[6]​ Es considerado uno de los Padres Fundadores de los Estados Unido ...

[ZH] 乔治·华盛顿
乔治·华盛顿（英語：George Washington，1732年2月22日—1799年12月14日），1775年至1783年美國獨立戰爭時的陆军總司令。於1789年成為首任美利坚合众国总统（同時亦為全世界首位以「總統」為稱謂之國家元首），在接連兩次選舉中，均獲得全體選舉人團無異議支持，一直擔任總統直至1797年，為至今唯一一位獲得所有選舉人團支持而當選的美國總統。
華盛頓早年曾於英軍服役擔任軍官，並參與七年戰爭北美戰線，之後在美國獨立戰爭中率領大陸軍團贏得美國獨立，他拒絕一些同僚希望他領導軍事政權的提議，於1783年回到維農山莊恢復平民生活。由於他扮演美國獨立戰爭和建國中最重要的角色，華盛頓通常被稱為「美国开国元勋」之一。
华盛顿在1789年通过和批准《美国宪法》以取代《邦联条例》的过程中发挥了不可或缺的作用。
华盛顿同样是具有争议的歷史人物。尽管華盛頓曾私下表达过对奴隶制的不满，但去世前仍然是拥有317个黑奴的大奴隶主。在美国独立战争期间，华盛顿下令组织了沙利文远征，进攻易洛魁联盟中除了塔斯卡洛拉和奥奈达之外的其余四个原住民部落，易洛魁人称呼他“城镇摧毁者”，并被批评为积极参与对北 ...

[HI] जॉर्ज वॉशिंगटन
जार्ज वाशिंगटन (अंग्रेज़ी: George Washington) (जन्म: २२ फरवरी, १७३२ मृत्यु: १४ दिसंबर १७९९) संयुक्त राज्य अमेरिका के पहले राष्ट्रपति थे। उन्होंने अमेरिकी सेना का नेतृत्व करते हुए ब्रिटेन के ऊपर अमरीकी क्रान्ति (१७७५-१७८३) में विजय हासिल की। उन्हें १७८९ में अमरीका का पहला राष्ट्रपति चुना गया।
आज भी अमरीका में उनके नाम का सिक्का चलता है।


== प्रारम्भिक जीवन ==
उनकी माता का नाम मैरी बॉल और पिता का नाम औगस्टाइन वॉशिंगटन था। वे दोनो एक स्थानीय विश्वविद्यालय में शिक्षक थे। बतौर बालक, वॉशिंगटन ने बहुत ...

=== Q2013 ===

[EN] Wikidata
Wikidata is a collaboratively edited multilingual knowledge graph hosted by the Wikimedia Foundation. It is a common source of open data that Wikimedia projects such as Wikipedia, and anyone else, is able to use under the CC0 public domain license. Wikidata is a wiki powered by the software MediaWiki, including its extension for semi-structured data, the Wikibase. As of early-2025, Wikidata had 1.65 billion item statements (semantic triple).


== Concept ==

Wikidata is a document-oriented datab ...

[DE] Wikidata
Wikidata ist eine frei bearbeitbare Wissensdatenbank, die unter anderem das Ziel hat, Wikipedia zu unterstützen. Das Projekt wurde von Wikimedia Deutschland gestartet und stellt als gemeinsame Quelle bestimmte Datentypen für Wikimedia-Projekte bereit, zum Beispiel Geburtsdaten oder sonstige allgemeingültige Daten, die in allen Artikeln der Wikimedia-Projekte verwendet werden können.
Seit dem Start 2012 verzeichnet Wikidata ein starkes Wachstum an Einträgen, seit 2022 sind mehr als 100 Millionen  ...

[ES] Wikidata
Wikidata es una base de conocimientos editada en colaboración y alojada por la Fundación Wikimedia. Tiene el objetivo de proporcionar una fuente común de datos que puedan ser utilizados por proyectos de Wikimedia como Wikipedia,[1]​[2]​ y por cualquier otra persona, bajo una licencia CC0 de dominio público. Esto es similar a la forma en que Wikimedia Commons proporciona almacenamiento para archivos multimedia y acceso a estos archivos para todos los proyectos de Wikimedia. Wikidata funciona y op ...

[ZH] 维基数据
維基數據（英語：Wikidata）是一個可協同編輯的知識庫，是繼2006年的維基學院之後，第一個新的維基媒體基金會項目。這一項目與維基共享資源的工作方式類似，將為其他維基計劃及各語種維基百科中的信息框、列表及跨語言連結等提供統一存放的數據，該項目在2012年10月30日投入使用。维基數據藉由軟體Wikibase運行。


== 背景 ==
这一项目最初由德国维基媒体协会启动，其目的在于为维基百科中的条目提供可调用的创建日期或是其他经验证后的数据。
艾倫人工智能研究所、戈登與貝蒂·摩爾基金會和Google公司向该计划提供了130万欧元的资助。


== 概念 ==

维基数据的开发工作主要分为三个阶段：

集中儲存跨語言連結
为所有语言维基百科中的信息框提供数据
利用维基数据中的数据创建及更新条目
維基數據是一個面向文档的數據庫，重點圍繞項目。每個項目都代表一個主題（或用於維持維基百科的管理頁面），是由一個唯一的號碼，前面加上字母Q；例如，政治話題的唯一項目编号是Q7163。這使得識別項目涵蓋不會偏袒任何語言翻譯的話題所需的基本信息。
信息是透過建立報表新增至項目。聲明採取的形式鍵-值對 ...

[HI] विकिडेटा
विकिडेटा अथवा विकिडाटा (अंग्रेज़ी: Wikidata) विश्व भर के लोगों के स्वैच्छिक सहयोग से निर्मित हो रहा एक ज्ञान आधार (नॉलेज बेस) है। यह विकिमिडिया फाउंडेशन द्वारा आयोजित है। यह मुक्त/मुफ़्त आंकड़ों का एक सर्वसुलभ स्रोत है जिसका उपयोग विकिपीडिया भी करता है। अन्य लोग भी इसका उपयोग निःशुल्क तथा सार्वजनिक लाइसेन्स के अन्तर्गत कर सकते हैं। जिस प्रकार विकिमिडिया कामन्स मीडिया फाइलों का भंडारण करती है तथा जिसका उपयोग विकिपीडिया के सभी प्रकल्प करते हैं, उसी प्रकार विकिडेटा भी सभी के लिए निःशुल्क आंकड़े भंड ...

=== Q45 ===

[EN] Portugal
Portugal, officially the Portuguese Republic, is a country in the Iberian Peninsula in Southwestern Europe. Featuring the westernmost point in continental Europe, Portugal borders Spain to its north and east, with which it shares the longest uninterrupted border in the European Union; to the south and the west is the North Atlantic Ocean; and to the west and southwest lie the Macaronesian archipelagos of the Azores and Madeira, which are the two autonomous regions of Portugal. Lisbon is the capi ...

[DE] Portugal
Portugal (portugiesisch Portugal [puɾtuˈɣal], amtlich Portugiesische Republik, portugiesisch República Portuguesa) ist ein europäischer Staat im Westen der Iberischen Halbinsel. In Portugal befindet sich der westlichste Punkt Kontinentaleuropas. Das Land wird folglich im Westen vom Atlantik begrenzt, im Osten und Norden von Spanien und im Süden auch vom Atlantischen Ozean. Zum portugiesischen Staatsgebiet gehören die Inseln der Azoren und Madeira (mit Porto Santo).
Portugal ist Gründungsmitglied ...

[ES] Portugal
Portugal (pronunciación en portugués: /puɾtuˈɣaɫ/ ()), oficialmente la República  Portuguesa, es un país soberano, ubicado en el suroeste de Europa, en la península ibérica. Es uno de los veintisiete Estados soberanos que forman la Unión Europea. Su capital y ciudad más poblada es Lisboa. Limita al este y al norte con España, y al sur y al oeste con el océano Atlántico. Su territorio comprende también los archipiélagos autónomos de las Azores y Madeira, situados en el océano Atlántico Norte. Su  ...

[ZH] 葡萄牙
葡萄牙共和國（葡萄牙語：República Portuguesa），簡稱葡萄牙或葡國（Portugal [puɾtuˈɣaɫ]），是位於西南歐伊比利亞半島上的一個共和制國家，實行單一制和半總統制政體，以里斯本為首都。葡萄牙的西部及南部瀕臨大西洋，北部及東部則與西班牙相接，本土總面積達92,212平方公里（35,672平方英里），而地處里斯本以西的羅卡角則為歐洲大陸的最西端。除了本土之外，位於大西洋的亞速爾群島和馬德拉群島為葡萄牙地方政府管轄的兩個重要自治區，也是葡萄牙領土的一部分。
现今的葡萄牙和大多數歐洲國家一樣曾屬於罗马帝国，在羅馬滅亡後又迎來西哥特人和苏维汇人的定居，多方势力相互角鬥；8世纪时，摩尔人征服了伊比利亚半岛的大部分地区，残留在半岛上的天主教国家随即开启了针对伊斯兰教国家的收复失地运动。1139年葡萄牙王国正式成立，并由北而南逐步完成征服。16世纪起，葡萄牙成为重要的海上强国，全盛时期为欧洲的经济、政治和军事大国。在现存的所有欧洲国家之中，葡萄牙的殖民历史是最为悠久的，延续近600年，且曾建立庞大的殖民帝国，包括今日53个国家的部分领土，其官方语言葡萄牙语现今为世界第6 ...

[HI] पुर्तगाल
पुर्तगाली गणराज्य यूरोप खंड में स्थित देश है। यह देश स्पेन के साथ आइबेरियन प्रायद्वीप बनाता है। इस राष्ट्र का भाषा पुर्तगाली भाषा है। इस राष्ट्र का राजधानी लिस्बन है।
पुर्तगाल दक्षिण-पश्चिमी यूरोप में इबेरियन प्रायद्वीप पर स्थित एक देश है, और जिसके क्षेत्र में अज़ोरेस और मदीरा के मैकरोनेशियन द्वीपसमूह भी शामिल हैं। यह महाद्वीपीय यूरोप में सबसे पश्चिमी बिंदु है, इसकी मुख्य भूमि पश्चिम और दक्षिण सीमा उत्तरी अटलांटिक महासागर के साथ है और उत्तर और पूर्व में, पुर्तगाल-स्पेन सीमा यूरोपीय संघ में सबसे ...

### Also adding a cleaning step

In [ ]:
import requests
import time
import csv

# Your list of entities
entities = [
    {'qid': 'Q31', 'enwiki': 'Belgium', 'dewiki': 'Belgien', 'eswiki': 'Bélgica', 'zhwiki': '比利时', 'hiwiki': 'बेल्जियम'},
    {'qid': 'Q8', 'enwiki': 'Happiness', 'dewiki': 'Glück', 'eswiki': 'Felicidad', 'zhwiki': '幸福', 'hiwiki': 'प्रसन्नता'},
    {'qid': 'Q23', 'enwiki': 'George Washington', 'dewiki': 'George Washington', 'eswiki': 'George Washington', 'zhwiki': '乔治·华盛顿', 'hiwiki': 'जॉर्ज वॉशिंगटन'},
    {'qid': 'Q2013', 'enwiki': 'Wikidata', 'dewiki': 'Wikidata', 'eswiki': 'Wikidata', 'zhwiki': '维基数据', 'hiwiki': 'विकिडेटा'},
    {'qid': 'Q45', 'enwiki': 'Portugal', 'dewiki': 'Portugal', 'eswiki': 'Portugal', 'zhwiki': '葡萄牙', 'hiwiki': 'पुर्तगाल'}
]

# File setup
output_file = 'wiki_extracts.csv'
fieldnames = ['qid', 'language', 'title', 'extract']

# Wikipedia API fetch function
def fetch_extract(lang_code, title):
    url = f"https://{lang_code}.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "prop": "extracts",
        "format": "json",
        "titles": title,
        "explaintext": 1
    }
    headers = {
        "User-Agent": "YourAppName/1.0 (mailto:your@email.com)"
    }
    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()
        page = next(iter(data["query"]["pages"].values()))
        return page.get("extract", "")
    except Exception as e:
        return f"ERROR: {e}"

In [ ]:
import re

def clean_wikipedia_text(text):
    # Remove section headers
    text = re.sub(r'==+[^=]+==+', '', text)

    # Remove excessive whitespace
    text = re.sub(r'\s+', ' ', text)

    # Stop at the References or See also section
    for section in ['References', 'See also', 'External links', 'Footnotes', 'Bibliography']:
        text = re.split(rf'\b{section}\b', text, flags=re.IGNORECASE)[0]

    return text.strip()

In [ ]:
# Write to CSV
with open(output_file, mode='w', encoding='utf-8', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()

    for entity in entities:
        print(f"\n=== {entity['qid']} ===")
        for lang_key in ['enwiki', 'dewiki', 'eswiki', 'zhwiki', 'hiwiki']:
            lang_code = lang_key[:2]
            title = entity[lang_key]
            print(f"Fetching [{lang_code.upper()}] {title} ...")
            extract = fetch_extract(lang_code, title)
            cleaned = clean_wikipedia_text(extract)
            print(f"Length: {len(cleaned)} chars (cleaned)")

            writer.writerow({
                            "qid": entity["qid"],
                            "language": lang_code,
                            "title": title,
                            "extract": cleaned
                            })

            time.sleep(1.5)  # Avoid hitting rate limits

=== Q31 ===
Fetching [EN] Belgium ...
Length: 60625 chars (cleaned)
Fetching [DE] Belgien ...
Length: 74378 chars (cleaned)
Fetching [ES] Bélgica ...
Length: 92773 chars (cleaned)
Fetching [ZH] 比利时 ...
Length: 6521 chars (cleaned)
Fetching [HI] बेल्जियम ...
Length: 34092 chars (cleaned)

=== Q8 ===
Fetching [EN] Happiness ...
Length: 38475 chars (cleaned)
Fetching [DE] Glück ...
Length: 64083 chars (cleaned)
Fetching [ES] Felicidad ...
Length: 30272 chars (cleaned)
Fetching [ZH] 幸福 ...
Length: 6921 chars (cleaned)
Fetching [HI] प्रसन्नता ...
Length: 972 chars (cleaned)

=== Q23 ===
Fetching [EN] George Washington ...
Length: 61805 chars (cleaned)
Fetching [DE] George Washington ...
Length: 63271 chars (cleaned)
Fetching [ES] George Washington ...
Length: 70686 chars (cleaned)
Fetching [ZH] 乔治·华盛顿 ...
Length: 15428 chars (cleaned)
Fetching [HI] जॉर्ज वॉशिंगटन ...
Length: 1132 chars (cleaned)

=== Q2013 ===
Fetching [EN] Wikidata ...
Length: 2945 chars (cleaned)
Fetching [DE] Wikidata ...
Length: 11293 chars (cleaned)
Fetching [ES] Wikidata ...
Length: 6192 chars (cleaned)
Fetching [ZH] 维基数据 ...
Length: 569 chars (cleaned)
Fetching [HI] विकिडेटा ...
Length: 1080 chars (cleaned)

=== Q45 ===
Fetching [EN] Portugal ...
Length: 31786 chars (cleaned)
Fetching [DE] Portugal ...
Length: 109042 chars (cleaned)
Fetching [ES] Portugal ...
Length: 89927 chars (cleaned)
Fetching [ZH] 葡萄牙 ...
Length: 11936 chars (cleaned)
Fetching [HI] पुर्तगाल ...
Length: 1020 chars (cleaned)

# Final Version

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Fetch QIDs and titels
  
Use the wikidata entity dump to fetch QIDs and titels  
only fetch the data that contains the required 5 languages  
1000 QIDs * 5 languages = 5000 articles

In [ ]:
import requests
import bz2
import json

# URL of the compressed dump
url = "https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.json.bz2"

# Fetch the compressed data in chunks
response = requests.get(url, stream=True)

# Create a decompressor instance for bz2 data
decompressed = bz2.BZ2Decompressor()

# Define the languages we're interested in
lang_keys = ['enwiki', 'dewiki', 'eswiki', 'zhwiki', 'hiwiki']

# Initialize counters and buffers
count = 0
buffer = b""
entities = []

# Loop through chunks of data from the response
for chunk in response.iter_content(4096):
    buffer += decompressed.decompress(chunk)

    # Process each line when it's complete (lines are separated by newline characters)
    while b"\n" in buffer:
        line, buffer = buffer.split(b"\n", 1)
        try:
            line = line.decode("utf-8").strip().rstrip(',')
            if line.startswith('{'):
                obj = json.loads(line)
                sitelinks = obj.get("sitelinks", {})

                # Check if all required language sitelinks are available
                if all(lang in sitelinks for lang in lang_keys):
                    # Extract the required information and append it to the entities list
                    entity = {
                        "qid": obj["id"],
                        **{lang: sitelinks[lang]["title"] for lang in lang_keys}
                    }
                    entities.append(entity)

                    count += 1
                    if count >= 1000:
                        print("Reached 1000 entities. Stopping.")
                        break  # Exit the while loop if processed the desired number of articles
        except Exception:
            # If there is an error in processing (e.g., invalid line), skip to the next line
            continue

    # Break the outer loop if the limit is reached
    if count >= 1000:
        break

Reached 1000 articles. Stopping.

## Extract articles
Use Wikipedia API to extract articles based on the QID and titles

In [ ]:
import requests
import time
import csv


# File setup
output_file = '/content/drive/My Drive/wikipedia/wiki_extracts.csv'
fieldnames = ['qid', 'language', 'title', 'extract']

# Wikipedia API fetch function
def fetch_extract(lang_code, title):
    url = f"https://{lang_code}.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "prop": "extracts",
        "format": "json",
        "titles": title,
        "explaintext": 1
    }
    headers = {
        "User-Agent": "WikiArticlesExtractor/1.0 (mailto:huan.liu2@uzh.ch)"
    }
    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()
        page = next(iter(data["query"]["pages"].values()))
        return page.get("extract", "")
    except Exception as e:
        return f"ERROR: {e}"

## Clean the extracted articles
Remove the markup and references

In [ ]:
import re

def clean_wikipedia_text(text):
    # Remove section headers (markup)
    text = re.sub(r'==+[^=]+==+', '', text)

    # Remove excessive whitespace
    text = re.sub(r'\s+', ' ', text)

    # Stop at the References or See also section
    for section in ['References', 'See also', 'External links', 'Footnotes', 'Bibliography']:
        text = re.split(rf'\b{section}\b', text, flags=re.IGNORECASE)[0]

    return text.strip()

## Extract and save the data
Save the extracted data as a csv file.

In [ ]:
from tqdm import tqdm
import time
import csv

# Write to CSV
with open(output_file, mode='w', encoding='utf-8', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()

    for entity in tqdm(entities, desc="Processing entities"):
        for lang_key in ['enwiki', 'dewiki', 'eswiki', 'zhwiki', 'hiwiki']:
            lang_code = lang_key[:2]
            title = entity[lang_key]
            extract = fetch_extract(lang_code, title)
            cleaned = clean_wikipedia_text(extract)

            writer.writerow({
                "qid": entity["qid"],
                "language": lang_code,
                "title": title,
                "extract": cleaned
            })

            time.sleep(1.5)  # Avoid hitting rate limits

Processing entities: 100%|██████████| 1000/1000 [2:27:05<00:00,  8.83s/it]

## Add categories

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import requests
from tqdm import tqdm
import time

In [ ]:
file_path = '/content/drive/My Drive/wikipedia/wiki_extracts.csv'

wiki = pd.read_csv(file_path)

wiki.head()

   qid language     title                                            extract
0  Q31       en   Belgium  Belgium, officially the Kingdom of Belgium, is...
1  Q31       de   Belgien  Belgien (amtlich Königreich Belgien, niederlän...
2  Q31       es   Bélgica  Bélgica (en neerlandés: ; en francés: ; en ale...
3  Q31       zh       比利时  比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...
4  Q31       hi  बेल्जियम  बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...

In [ ]:
# Function to fetch instance-of QIDs (P31)
def get_instance_of(qid):
    url = "https://www.wikidata.org/w/api.php"
    params = {
        "action": "wbgetclaims",
        "entity": qid,
        "property": "P31",  # instance of
        "format": "json"
    }
    headers = {
        "User-Agent": "WikiTopicsFetcher/1.0 (mailto:huan.liu2@uzh.ch)"
    }

    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()
        claims = data.get("claims", {}).get("P31", [])
        topic_ids = [claim['mainsnak']['datavalue']['value']['id']
                     for claim in claims if 'datavalue' in claim['mainsnak']]
        return topic_ids
    except Exception as e:
        return [f"ERROR: {e}"]

In [ ]:
def get_labels_for_qids(qid_list, lang='en'):
    url = "https://www.wikidata.org/w/api.php"
    headers = {
        "User-Agent": "WikiTopicsFetcher/1.0 (mailto:huan.liu2@uzh.ch)"
    }
    label_map = {}

    # Split into batches of 50
    for i in range(0, len(qid_list), 50):
        batch = qid_list[i:i+50]
        params = {
            "action": "wbgetentities",
            "ids": "|".join(batch),
            "props": "labels",
            "languages": lang,
            "format": "json"
        }

        try:
            response = requests.get(url, params=params, headers=headers)
            response.raise_for_status()
            data = response.json()

            for qid in batch:
                label = data.get("entities", {}).get(qid, {}).get("labels", {}).get(lang, {}).get("value")
                if label:
                    label_map[qid] = label
        except Exception as e:
            print(f"Error fetching batch {i//50 + 1}: {e}")
            time.sleep(1)

        time.sleep(0.5)  # avoid being rate-limited

    return label_map

In [ ]:
# test whether this functions works
all_instance_qids = ['Q3624078', 'Q43702', 'Q6256', 'Q20181813', 'Q1250464']
labels = get_labels_for_qids(all_instance_qids, lang='en')
print(labels)

{'Q3624078': 'sovereign state', 'Q43702': 'federation', 'Q6256': 'country', 'Q20181813': 'colonial power', 'Q1250464': 'realm'}

In [ ]:
# Step 1: Fetch all instance-of QIDs
qid_to_instance = {}
for qid in tqdm(wiki['qid'].unique(), desc="Fetching instance-of QIDs"):
    qid_to_instance[qid] = get_instance_of(qid)

# Step 2: Collect all unique instance QIDs
all_instance_qids = set(qid for qids in qid_to_instance.values() for qid in qids if not qid.startswith("ERROR"))

# Step 3: Map instance QIDs to human-readable labels
qid_to_label = get_labels_for_qids(list(all_instance_qids))

# Step 4: Map instance QIDs to labels for each row
def label_list(qids):
    return [qid_to_label.get(qid, qid) for qid in qids]

wiki['semantic_qids'] = wiki['qid'].map(qid_to_instance)
wiki['semantic_labels'] = wiki['semantic_qids'].apply(lambda qids: label_list(qids) if isinstance(qids, list) else qids)

Fetching instance-of QIDs: 100%|██████████| 1000/1000 [02:47<00:00,  5.99it/s]

In [ ]:
# Step 5: Save
output_path = "/content/drive/My Drive/wikipedia/wiki_extracts_with_labels.csv"
wiki.to_csv(output_path, index=False)

In [ ]:
wiki_data = pd.read_csv(output_path)
wiki_data.head()

,qid,language,title,extract,semantic_qids,semantic_labels
0,Q31,en,Belgium,"Belgium, officially the Kingdom of Belgium, is...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."
1,Q31,de,Belgien,"Belgien (amtlich Königreich Belgien, niederlän...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."
2,Q31,es,Bélgica,Bélgica (en neerlandés: ; en francés: ; en ale...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."
3,Q31,zh,比利时,比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."
4,Q31,hi,बेल्जियम,"बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."

## Model

### Load the data

In [ ]:
import pandas as pd

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = "/content/drive/My Drive/wikipedia/wiki_extracts_with_labels.csv"

wiki = pd.read_csv(file_path)

wiki.head()

,qid,language,title,extract,semantic_qids,semantic_labels
0,Q31,en,Belgium,"Belgium, officially the Kingdom of Belgium, is...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."
1,Q31,de,Belgien,"Belgien (amtlich Königreich Belgien, niederlän...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."
2,Q31,es,Bélgica,Bélgica (en neerlandés: ; en francés: ; en ale...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."
3,Q31,zh,比利时,比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."
4,Q31,hi,बेल्जियम,"बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '..."

### Set Up the Zero-Shot Classification Pipeline

The model facebook/bart-large-mnli is a version of BART (Bidirectional and Auto-Regressive Transformers) fine-tuned on the Multi-Genre Natural Language Inference (MNLI) dataset.    
The model is trained to understand relationships between premises and hypotheses, which enables the following trick for classification:
You provide your input text as the "premise".
Each candidate label becomes a hypothesis, like:
"This text is about gender bias."
The model evaluates how entailment, neutral, or contradiction the relationship is between the premise and each hypothesis.
This allows it to predict whether a text implies a certain label — without any task-specific fine-tuning.

#### Experiment with the following type of biases

 Framing bias: Differences in how events/facts are presented or emphasized (e.g. choice of verbs/adjectives).  
Omission bias: Facts or viewpoints present in one language article but missing entirely in another.  
Coverage bias: Disparities in article length, section counts, or citation counts across languages.  
Source bias: Reliance on different types or credibility levels of sources (e.g. local vs. international).  
Ideological bias: Slant toward a particular political or philosophical viewpoint beyond mere “political bias.”  
Nationalistic bias: Excessive patriotism or negative framing of other countries.
Religious bias: Favorable/unfavorable language toward a religion or its adherents.  
Economic bias: Tendency to portray economic systems or companies in a consistently positive/negative light.  
Structural bias: Where key sections (e.g. History, Culture, Criticism) appear in one language but not another.  
Sensationalist bias: Overuse of dramatic or emotionally charged wording.

Removing some bias types:  
ideological bias	Broad term — overlaps heavily with political, religious, and economic bias.  
nationalist bias	Often a subtype of political bias or cultural bias.  religious bias	May be retained depending on your dataset focus — otherwise often part of cultural or ideological bias.  
economic bias	Frequently overlaps with ideological bias and may be rare in general Wikipedia text.  
structural bias	Difficult to detect in article-level text; better suited for analyzing entire editorial systems.  
sensationalist bias	More relevant in tabloid/news content than Wikipedia. Hard to detect in encyclopedic tone.

In [ ]:
from transformers import pipeline
from datasets import Dataset
import pandas as pd

# Initialize the zero-shot classification pipeline
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

Device set to use cuda:0

In [ ]:
# Define candidate labels for bias detection (these can be adjusted based on the bias types to be detected)
# candidate_labels = ["gender bias", "racial bias", "political bias", "age bias", "cultural bias", "framing bias", "omission bias", "coverage bias","source bias", "ideological bias","nationalist bias","religious bias","economic bias","structural bias","sensationalist bias"]
candidate_labels = ["gender bias", "racial bias", "political bias", "age bias", "cultural bias", "framing bias", "omission bias", "coverage bias"]

'\nBias Type\nFraming bias\nDifferences in how events/facts are presented or emphasized (e.g. choice of verbs/adjectives).\nOmission bias\nFacts or viewpoints present in one language article but missing entirely in another.\nCoverage bias\nDisparities in article length, section counts, or citation counts across languages.\nSource bias\nReliance on different types or credibility levels of sources (e.g. local vs. international).\nIdeological bias\nSlant toward a particular political or philosophical viewpoint beyond mere “political bias.”\nNationalistic bias\nExcessive patriotism or negative framing of other countries.\nReligious bias\nFavorable/unfavorable language toward a religion or its adherents.\nEconomic bias\nTendency to portray economic systems or companies in a consistently positive/negative light.\nStructural bias\nWhere key sections (e.g. History, Culture, Criticism) appear in one language but not another.\nSensationalist bias\nOveruse of dramatic or emotionally charged wording.\n'

In [ ]:
# Loop through the articles and classify them
from tqdm import tqdm

wiki["bias_detection_result"] = None  # Create the column with default empty values

for index, row in tqdm(wiki.iterrows(), total=len(wiki)):
    article_text = row["extract"]
    # Skip empty or NaN text, code has broken down before, ther are empty ones
    if pd.isna(article_text) or not isinstance(article_text, str) or article_text.strip() == "":
        continue
    result = classifier(article_text, candidate_labels)
    wiki.at[index, "bias_detection_result"] = result

  0%|          | 2/4956 [00:05<3:49:43,  2.78s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
100%|██████████| 4956/4956 [2:37:18<00:00,  1.90s/it]

In [ ]:
wiki.head(5)

,qid,language,title,extract,semantic_qids,semantic_labels,bias_detection_result,average_bias_score
0,Q31,en,Belgium,"Belgium, officially the Kingdom of Belgium, is...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","{'sequence': 'Belgium, officially the Kingdom ...",None
1,Q31,de,Belgien,"Belgien (amtlich Königreich Belgien, niederlän...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': 'Belgien (amtlich Königreich Belg...,None
2,Q31,es,Bélgica,Bélgica (en neerlandés: ; en francés: ; en ale...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': 'Bélgica (en neerlandés: ; en fra...,None
3,Q31,zh,比利时,比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': '比利時王國（法語：Royaume de Belgique；荷蘭語...,None
4,Q31,hi,बेल्जियम,"बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","{'sequence': 'बेल्जियम (डच: België, फ़्रांसीसी...",None

In [ ]:
wiki = wiki.drop(columns="average_bias_score") # drop this column at this step

In [ ]:
wiki.to_csv("/content/drive/My Drive/wikipedia/wiki_0512.csv", index=False) # save the file

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import ast  # For safely parsing stringified dicts

# Load the CSV
wiki = pd.read_csv("/content/drive/My Drive/wikipedia/wiki_0512.csv")

# Convert string to dict
wiki["bias_detection_result"] = wiki["bias_detection_result"].apply(ast.literal_eval)

# Extract {label: score} as a new dict for each row
bias_expanded = wiki["bias_detection_result"].apply(
    lambda x: dict(zip(x["labels"], x["scores"]))
)

# Convert to DataFrame
bias_df = pd.DataFrame(bias_expanded.tolist())

# Compute the most dominant bias score (max score per row)
bias_df["max_bias"] = bias_df.max(axis=1)

# Compute the label with the highest bias score
bias_df["top_bias"] = bias_df.idxmax(axis=1)

# Combine with original DataFrame
wiki = pd.concat([wiki, bias_df], axis=1)

In [ ]:
wiki.sample(5)

,qid,language,title,extract,semantic_qids,semantic_labels,bias_detection_result,framing bias,coverage bias,cultural bias,political bias,age bias,racial bias,gender bias,omission bias,max_bias,top_bias
3742,Q23795,de,977,Kaiser Otto II. führt einen Feldzug gegen Böhm...,['Q577'],['year'],{'sequence': 'Kaiser Otto II. führt einen Feld...,0.167575,0.130976,0.143050,0.097330,0.120915,0.118146,0.129481,0.092528,0.167575,framing bias
837,Q2640,hi,१० हायजीया,१० हायजीया (10 Hygiea) हमारे सौर मंडल का चौथा ...,['Q3863'],['asteroid'],{'sequence': '१० हायजीया (10 Hygiea) हमारे सौर...,0.248120,0.183436,0.076611,0.054326,0.146458,0.062384,0.099990,0.128674,0.248120,framing bias
2878,Q13434,hi,अभ्रयंती तारा,"अभ्रयंती या माया (Maia), जिसका बायर नामांकन २०...","['Q3037794', 'Q66521853', 'Q67206691', 'Q21545...","['optical double', 'suspected variable', 'infr...","{'sequence': 'अभ्रयंती या माया (Maia), जिसका ब...",0.178359,0.130303,0.124767,0.082940,0.042008,0.190191,0.134006,0.117427,0.190191,racial bias
356,Q1044,es,Sierra Leona,Sierra Leona o Sierra Leone (en inglés: Sierra...,"['Q7270', 'Q3624078', 'Q6256']","['republic', 'sovereign state', 'country']",{'sequence': 'Sierra Leona o Sierra Leone (en ...,0.201337,0.214236,0.095830,0.112450,0.123997,0.081685,0.111903,0.058562,0.214236,coverage bias
4770,Q34726,zh,希腊神话,希腊神話（英語：Greek mythology，希臘語：ελληνική μυθολογία...,['Q9134'],['mythology'],{'sequence': '希腊神話（英語：Greek mythology，希臘語：ελλη...,0.172542,0.142164,0.131754,0.092222,0.137155,0.103745,0.122783,0.097634,0.172542,framing bias

In [ ]:
# Sort the DataFrame by 'max_bias' in descending order
bias_df_sorted = bias_df.sort_values(by="max_bias", ascending=False)

# Display the sorted DataFrame
bias_df_sorted.head()

,framing bias,coverage bias,cultural bias,political bias,age bias,racial bias,gender bias,omission bias,max_bias,top_bias
1609,0.094467,0.083980,0.056814,0.040971,0.059987,0.042298,0.046280,0.575204,0.575204,omission bias
4700,0.095314,0.063449,0.057928,0.485519,0.040918,0.158519,0.031251,0.067102,0.485519,political bias
587,0.093847,0.047662,0.048910,0.035655,0.098034,0.120083,0.463905,0.091904,0.463905,gender bias
4624,0.421837,0.137889,0.077621,0.049465,0.101262,0.087617,0.062090,0.062220,0.421837,framing bias
4649,0.406135,0.188609,0.058995,0.025452,0.061648,0.034688,0.060961,0.163512,0.406135,framing bias

#### Grouping biases

Group	Biases:  
Social Bias, including gender bias, racial bias, age bias  
Media Bias:	framing bias, omission bias, coverage bias

Why grouping biases:  
Improves classification confidence: Fewer, more distinct labels reduce overlap and confusion for the model.  
Simplifies output: Easier to interpret and act on three broad categories than eight specific ones.

In [ ]:
from transformers import pipeline
from datasets import Dataset
import pandas as pd
from tqdm import tqdm

In [ ]:
candidate_labels = ["social bias", "political bias", "cultural bias", "media bias"]

In [ ]:
# Initialize the zero-shot classification pipeline
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cuda:0

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
file_path = "/content/drive/My Drive/wikipedia/wiki_extracts_with_labels.csv"

wiki = pd.read_csv(file_path)

In [ ]:
wiki["bias_detection_result"] = None  # Create the column with default empty values

for index, row in tqdm(wiki.iterrows(), total=len(wiki)):
    article_text = row["extract"]
    # Skip empty or NaN text, code has broken down before, ther are empty ones
    if pd.isna(article_text) or not isinstance(article_text, str) or article_text.strip() == "":
        continue
    result = classifier(article_text, candidate_labels)
    wiki.at[index, "bias_detection_result"] = result

In [ ]:
# Loop through the articles and classify them

# Filter out invalid or empty text rows first
wiki = wiki[wiki["extract"].apply(lambda x: isinstance(x, str) and x.strip() != "")].copy()

wiki["bias_detection_result"] = None  # Create the column with default empty values

for index, row in tqdm(wiki.iterrows(), total=len(wiki)):
    article_text = row["extract"]
    # Skip empty or NaN text, code has broken down before, ther are empty ones
    if pd.isna(article_text) or not isinstance(article_text, str) or article_text.strip() == "":
        continue
    result = classifier(article_text, candidate_labels)
    wiki.at[index, "bias_detection_result"] = result

100%|██████████| 4956/4956 [1:16:00<00:00,  1.09it/s]

In [ ]:
wiki.head(5)

,qid,language,title,extract,semantic_qids,semantic_labels,bias_detection_result
0,Q31,en,Belgium,"Belgium, officially the Kingdom of Belgium, is...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","{'sequence': 'Belgium, officially the Kingdom ..."
1,Q31,de,Belgien,"Belgien (amtlich Königreich Belgien, niederlän...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': 'Belgien (amtlich Königreich Belg...
2,Q31,es,Bélgica,Bélgica (en neerlandés: ; en francés: ; en ale...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': 'Bélgica (en neerlandés: ; en fra...
3,Q31,zh,比利时,比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': '比利時王國（法語：Royaume de Belgique；荷蘭語...
4,Q31,hi,बेल्जियम,"बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","{'sequence': 'बेल्जियम (डच: België, फ़्रांसीसी..."

In [ ]:
wiki.to_csv("/content/drive/My Drive/wikipedia/wiki_4biases.csv", index=False) # save the file

In [ ]:
import ast  # For safely parsing stringified dicts

# Load the CSV
wiki = pd.read_csv("/content/drive/My Drive/wikipedia/wiki_4biases.csv")

# Convert string to dict
wiki["bias_detection_result"] = wiki["bias_detection_result"].apply(ast.literal_eval)

# Extract {label: score} as a new dict for each row
bias_expanded = wiki["bias_detection_result"].apply(
    lambda x: dict(zip(x["labels"], x["scores"]))
)

# Convert to DataFrame
bias_df = pd.DataFrame(bias_expanded.tolist())

# Compute the most dominant bias score (max score per row)
bias_df["max_bias"] = bias_df.max(axis=1)

# Compute the label with the highest bias score
bias_df["top_bias"] = bias_df.idxmax(axis=1)

# Combine with original DataFrame
wiki = pd.concat([wiki, bias_df], axis=1)

In [ ]:
wiki.head()

,qid,language,title,extract,semantic_qids,semantic_labels,bias_detection_result,cultural bias,social bias,political bias,media bias,max_bias,top_bias
0,Q31,en,Belgium,"Belgium, officially the Kingdom of Belgium, is...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","{'sequence': 'Belgium, officially the Kingdom ...",0.256682,0.250067,0.248909,0.244342,0.256682,cultural bias
1,Q31,de,Belgien,"Belgien (amtlich Königreich Belgien, niederlän...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': 'Belgien (amtlich Königreich Belg...,0.253639,0.253194,0.291585,0.201582,0.291585,political bias
2,Q31,es,Bélgica,Bélgica (en neerlandés: ; en francés: ; en ale...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': 'Bélgica (en neerlandés: ; en fra...,0.266817,0.268748,0.245896,0.218538,0.268748,social bias
3,Q31,zh,比利时,比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': '比利時王國（法語：Royaume de Belgique；荷蘭語...,0.258528,0.290586,0.227636,0.223251,0.290586,social bias
4,Q31,hi,बेल्जियम,"बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","{'sequence': 'बेल्जियम (डच: België, फ़्रांसीसी...",0.267903,0.291670,0.249142,0.191286,0.291670,social bias

In [ ]:
# Sort the DataFrame by 'max_bias' in descending order
bias_df_sorted = bias_df.sort_values(by="max_bias", ascending=False)

# Display the sorted DataFrame
bias_df_sorted.head()

,cultural bias,social bias,political bias,media bias,max_bias,top_bias
4700,0.093374,0.080257,0.782614,0.043755,0.782614,political bias
4919,0.637661,0.157623,0.066689,0.138027,0.637661,cultural bias
4340,0.164091,0.570911,0.103905,0.161094,0.570911,social bias
2740,0.569146,0.222086,0.114315,0.094453,0.569146,cultural bias
4155,0.132670,0.558028,0.119071,0.190231,0.558028,social bias

#### Previous version from Dongyuan

In [ ]:
# Simplify: build a {label: score} dict
simple_scores = dict(zip(result["labels"], result["scores"]))
wiki.at[index, "bias_result_simplified"] = simple_scores

# Compute average_bias_score as the mean of all bias scores per article
'''
What this does:
	1.	For each row’s bias_result_simplified dict d, it
	•	Sums all the float values (sum(d.values()))
	•	Divides by the number of labels (len(d))
	2.	If the dict is missing or empty, it writes None.
	3.	Stores the result in the new column overall_bias_score.
'''
average_score=wiki["average_bias_score"] = wiki["bias_result_simplified"].apply(
    lambda d: sum(d.values()) / len(d) if isinstance(d, dict) and d else None
    )
# Inspect
wiki.loc[:, ["bias_result_simplified", "average_bias_score"]].head()

In [ ]:
wiki.head(5)

,qid,language,title,extract,semantic_qids,semantic_labels,bias_detection_result,bias_result_simplified,paragraph_bias_results,paragraph_bias_result,average_bias_score
0,Q31,en,Belgium,"Belgium, officially the Kingdom of Belgium, is...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","{'sequence': 'Belgium, officially the Kingdom ...","{'coverage bias': 0.09624740481376648, 'source...","[{'paragraph': 'Belgium, officially the Kingdo...","[{'paragraph': 'Belgium, officially the Kingdo...",0.066667
1,Q31,de,Belgien,"Belgien (amtlich Königreich Belgien, niederlän...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': 'Belgien (amtlich Königreich Belg...,"{'structural bias': 0.08952099084854126, 'econ...",[{'paragraph': 'Belgien (amtlich Königreich Be...,[{'paragraph': 'Belgien (amtlich Königreich Be...,0.066667
2,Q31,es,Bélgica,Bélgica (en neerlandés: ; en francés: ; en ale...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': 'Bélgica (en neerlandés: ; en fra...,"{'structural bias': 0.1157507449388504, 'cultu...",[{'paragraph': 'Bélgica (en neerlandés: ; en f...,[{'paragraph': 'Bélgica (en neerlandés: ; en f...,0.066667
3,Q31,zh,比利时,比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",{'sequence': '比利時王國（法語：Royaume de Belgique；荷蘭語...,"{'Framing bias': 0.08019299060106277, 'age bia...",[{'paragraph': '比利時王國（法語：Royaume de Belgique；荷...,[{'paragraph': '比利時王國（法語：Royaume de Belgique；荷...,0.066667
4,Q31,hi,बेल्जियम,"बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","{'sequence': 'बेल्जियम (डच: België, फ़्रांसीसी...","{'Framing bias': 0.10072648525238037, 'source ...","[{'paragraph': 'बेल्जियम (डच: België, फ़्रांसी...","[{'paragraph': 'बेल्जियम (डच: België, फ़्रांसी...",0.066667

In [ ]:

import re

def split_into_paragraphs(text):
    return [p.strip() for p in re.split(r'\n\s*\n', text) if p.strip()]

wiki["paragraph_bias_results"] = None  # changed to save para bias to a new column

# NOT Limit to first 5 articles
for index, row in tqdm(wiki.iterrows(), total=len(wiki)):
    article_text = row["extract"]
    # Check for invalid text, or empty
    if pd.isna(article_text) or not isinstance(article_text, str) or article_text.strip() == "":
        continue
    paragraphs = split_into_paragraphs(article_text)

    paragraph_results = []
    for para in paragraphs:
        if len(para.split()) < 2:
            continue  # Skip very short or meaningless paragraphs? or should we delete this line
        result = classifier(para, candidate_labels)
        paragraph_results.append({
            "paragraph": para,
            "classification": result
        })

    wiki.at[index, "paragraph_bias_results"] = paragraph_results

100%|██████████| 5/5 [00:25<00:00,  5.10s/it]

In [ ]:
# Inspect
wiki.loc[:5, ["extract", "bias_result_simplified", "paragraph_bias_results"]]

,extract,bias_result_simplified,paragraph_bias_results
0,"Belgium, officially the Kingdom of Belgium, is...","{'coverage bias': 0.09624740481376648, 'source...","[{'paragraph': 'Belgium, officially the Kingdo..."
1,"Belgien (amtlich Königreich Belgien, niederlän...","{'structural bias': 0.08952099084854126, 'econ...",[{'paragraph': 'Belgien (amtlich Königreich Be...
2,Bélgica (en neerlandés: ; en francés: ; en ale...,"{'structural bias': 0.1157507449388504, 'cultu...",[{'paragraph': 'Bélgica (en neerlandés: ; en f...
3,比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...,"{'Framing bias': 0.08019299060106277, 'age bia...",[{'paragraph': '比利時王國（法語：Royaume de Belgique；荷...
4,"बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...","{'Framing bias': 0.10072648525238037, 'source ...","[{'paragraph': 'बेल्जियम (डच: België, फ़्रांसी..."
5,Happiness is a complex and multifaceted emotio...,None,None

In [ ]:
wiki.head()

,qid,language,title,extract,semantic_qids,semantic_labels,bias_detection_result
0,Q31,en,Belgium,"Belgium, officially the Kingdom of Belgium, is...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","[{'paragraph': 'Belgium, officially the Kingdo..."
1,Q31,de,Belgien,"Belgien (amtlich Königreich Belgien, niederlän...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",[{'paragraph': 'Belgien (amtlich Königreich Be...
2,Q31,es,Bélgica,Bélgica (en neerlandés: ; en francés: ; en ale...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",[{'paragraph': 'Bélgica (en neerlandés: ; en f...
3,Q31,zh,比利时,比利時王國（法語：Royaume de Belgique；荷蘭語：Koninkrijk Be...,"['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...",[{'paragraph': '比利時王國（法語：Royaume de Belgique；荷...
4,Q31,hi,बेल्जियम,"बेल्जियम (डच: België, फ़्रांसीसी: Belgique, जर...","['Q3624078', 'Q43702', 'Q6256', 'Q20181813', '...","['sovereign state', 'federation', 'country', '...","[{'paragraph': 'बेल्जियम (डच: België, फ़्रांसी..."

# xlsx csv export result

In [ ]:
# install the Excel engine
# !pip install openpyxl --quiet

output_path = "/content/drive/My Drive/wikipedia/wiki_bias_detection_results.xlsx"
# Export DataFrame to Excel
wiki.to_excel(output_path, index=False, engine="openpyxl")
print(f"✅ Bias detection results exported to: {output_path}")

# CSV export path
csv_output_path = "/content/drive/My Drive/wikipedia/wiki_bias_detection_results.csv"
# Export DataFrame to CSV
wiki.to_csv(csv_output_path, index=False)

print(f"✅ Bias detection results also exported to: {csv_output_path}")

✅ Bias detection results exported to: /content/drive/My Drive/wikipedia/wiki_bias_detection_results.xlsx
✅ Bias detection results also exported to: /content/drive/My Drive/wikipedia/wiki_bias_detection_results.csv

## If more entities are needed, run the following code  
Load the previous QIDs and skip any already-seen QIDs to avoid duplicates  
In the following script, another 1000 entities are added

In [ ]:
import requests
import bz2
import json
import pandas as pd
import os
import time
import csv
import re
from tqdm import tqdm

In [ ]:
# Setup
url = "https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.json.bz2"
lang_keys = ['enwiki', 'dewiki', 'eswiki', 'zhwiki', 'hiwiki']
entities = []
count = 0
TARGET_COUNT = 1000
buffer = b""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Path to previous CSV
csv_path = "/content/drive/My Drive/wikipedia/wiki_extracts.csv"

# Load previously seen QIDs
previous_qids = set()
if os.path.exists(csv_path):
    df_prev = pd.read_csv(csv_path)
    previous_qids = set(df_prev['qid'].unique())

print(f"Loaded {len(previous_qids)} previously seen QIDs.")

# Start streaming and decompressing
response = requests.get(url, stream=True)
decompressed = bz2.BZ2Decompressor()

for chunk in response.iter_content(4096):
    buffer += decompressed.decompress(chunk)

    while b"\n" in buffer:
        line, buffer = buffer.split(b"\n", 1)
        try:
            line = line.decode("utf-8").strip().rstrip(',')
            if line.startswith('{'):
                obj = json.loads(line)
                qid = obj["id"]
                sitelinks = obj.get("sitelinks", {})

                # Skip already collected QIDs
                if qid in previous_qids:
                    continue

                # Only include if all languages are present
                if all(lang in sitelinks for lang in lang_keys):
                    entity = {
                        "qid": qid,
                        **{lang: sitelinks[lang]["title"] for lang in lang_keys}
                    }
                    entities.append(entity)
                    count += 1
                    if count >= TARGET_COUNT:
                        break
        except Exception:
            continue

    if count >= TARGET_COUNT:
        break

print(f"✅ Collected {count} new unique entities.")

In [ ]:
# File setup
output_file = '/content/drive/My Drive/wikipedia/wiki_extracts.csv'
fieldnames = ['qid', 'language', 'title', 'extract']

# Wikipedia API fetch function
def fetch_extract(lang_code, title):
    url = f"https://{lang_code}.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "prop": "extracts",
        "format": "json",
        "titles": title,
        "explaintext": 1
    }
    headers = {
        "User-Agent": "WikiArticlesExtractor/1.0 (mailto:huan.liu2@uzh.ch)"
    }
    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()
        page = next(iter(data["query"]["pages"].values()))
        return page.get("extract", "")
    except Exception as e:
        return f"ERROR: {e}"

In [ ]:
def clean_wikipedia_text(text):
    # Remove section headers
    text = re.sub(r'==+[^=]+==+', '', text)

    # Remove excessive whitespace
    text = re.sub(r'\s+', ' ', text)

    # Stop at the References or See also section
    for section in ['References', 'See also', 'External links', 'Footnotes', 'Bibliography']:
        text = re.split(rf'\b{section}\b', text, flags=re.IGNORECASE)[0]

    return text.strip()

In [ ]:
# Write to CSV
with open(output_file, mode='a', encoding='utf-8', newline='') as file: # mode='a' to append new data into the original csv file instead of overwriting it
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()

    for entity in tqdm(entities, desc="Processing entities"):
        for lang_key in ['enwiki', 'dewiki', 'eswiki', 'zhwiki', 'hiwiki']:
            lang_code = lang_key[:2]
            title = entity[lang_key]
            extract = fetch_extract(lang_code, title)
            cleaned = clean_wikipedia_text(extract)

            writer.writerow({
                "qid": entity["qid"],
                "language": lang_code,
                "title": title,
                "extract": cleaned
            })

            time.sleep(1.5)  # Avoid hitting rate limits